import { useState, SyntheticEvent } from "react"
import {
  Autocomplete,
  TextField,
  Button,
  Grid,
  AutocompleteChangeReason,
} from "@mui/material"
import { match } from "ts-pattern"

const QUALITY_OPTIONS = [
  "aberrant",
  "abolished",
  "decreased",
  "delayed",
  "development arrests at",
  "increased",
  "precocious",
  "wild type",
]

const ENTITY_OPTIONS = [
  "2,3-bisphosphoglycerate level",
  "3',5'-cyclic-AMP phosphodiesterase activity",
  "3',5'-cyclic-GMP phosphodiesterase activity",
  "ATP level",
  "G protein-coupled chemorepellent receptor signaling pathway",
  "G protein-coupled receptor signaling",
  "GABA signaling pathway",
  "GTPase activator activity",
  "GTPase regulator activity",
  "Golgi localization",
  "MPBD level",
  "Rab protein signal transduction",
  "Rac protein signal transduction",
  "Rap protein signal transduction",
  "Ras protein signal transduction",
  "STAT signaling pathway",
  "TORC2 signaling",
  "actin cytoskeleton organization",
  "actin filament bundle assembly",
  "actin filament depolymerization",
  "actin filament organization",
  "actin filament polymerization",
  "actin filament polymerization at leading edge",
  "actin filament sliding",
  "actin nucleation",
  "adaptation of signaling pathway",
  "adenylate cyclase activator activity",
  "adenylate cyclase activity",
  "adenylate cyclase regulator activity",
  "aggregation",
  "aggregation territory size",
  "autophagic cell death",
  "autophagic vacuole organization",
  "autophagosome maturation",
  "autophagosome organization",
  "autophagy",
  "basal disc formation",
  "binding",
  "bleb assembly",
  "cAMP binding",
  "cAMP biosynthesis",
  "cAMP level",
  "cGMP biosynthesis",
  "cGMP-mediated signaling",
  "calcium ion import",
  "calcium-dependent cell-cell adhesion",
  "calcium-independent cell-cell adhesion",
  "calcium-mediated signaling",
  "cell adhesion",
  "cell cycle",
  "cell death",
  "cell differentiation",
  "cell fate determination",
  "cell migration to prestalk region",
  "cell morphogenesis",
  "cell motility",
  "cell motility in response to calcium ion",
  "cell polarity",
  "cell projection biogenesis",
  "cell separation during cytokinesis",
  "cell-cell adhesion",
  "cell-cell recognition",
  "cell-cell self recognition",
  "cell-substrate adhesion",
  "cellular DNA damage response",
  "cellular defense response",
  "cellular homeostasis",
  "cellular hyperosmotic response",
  "cellular hypotonic response",
  "cellular localization",
  "cellular metabolic process",
  "cellular process",
  "cellular response to cation stress",
  "cellular response to extracellular stimulus",
  "cellular response to fluid shear stress",
  "cellular response to heat",
  "cellular response to hypoxia",
  "cellular response to nitrogen starvation",
  "cellular response to osmotic stress",
  "cellular response to starvation",
  "cellular response to stress",
  "cellular thermotolerance",
  "cellulose binding",
  "cellulose biosynthesis",
  "centromere complex assembly",
  "centrosome localization",
  "centrosome organization",
  "cheating during chimeric sorocarp development",
  "chemorepellent activity",
  "chemotaxis",
  "chemotaxis rate",
  "chemotaxis to arachidonic acid",
  "chemotaxis to cAMP",
  "chemotaxis to folate",
  "chromatin assembly",
  "co-transcriptional gene silencing by RNA interference machinery",
  "contractile vacuole discharge",
  "contractile vacuole dissociation from plasma membrane",
  "contractile vacuole localization",
  "contractile vacuole morphology",
  "contractile vacuole organization",
  "contractile vacuole size",
  "contractile vacuole tethering involved in discharge",
  "cortical actin cytoskeleton organization",
  "culmination",
  "cyclic nucleotide binding",
  "cytochrome C oxidase activity",
  "cytokinesis",
  "cytoskeleton organization",
  "cytoplasmic vesicle (protein localization to)",
  "DIF-1 biosynthesis",
  "DNA (cytosine-5-)-methyltransferase activity",
  "DNA repair",
  "DNA-methyltransferase activity",
  "defense response to Gram-negative bacterium",
  "defense response to Gram-positive bacterium",
  "defense response to bacterium",
  "defense response to fungus",
  "double-strand break repair",
  "double-strand break repair via homologous recombination",
  "double-strand break repair via nonhomologous end joining",
  "early culminant stage",
  "endocytic recycling",
  "endocytosis",
  "endolysosome (protein localization to)",
  "endoplasmic reticulum membrane organization",
  "endoplasmic reticulum organization",
  "endosomal transport",
  "endosomal vesicle fusion",
  "endosome morphology",
  "endosome size",
  "engulfment during phagocytosis",
  "epithelium-like organization",
  "establishment of cell polarity",
  "establishment or maintenance of cell polarity",
  "exocytosis",
  "extracellular cAMP signaling pathway",
  "fatty acid level",
  "filopodium formation",
  "folic acid binding",
  "fruiting body morphogenesis",
  "fruiting body size",
  "gene expression",
  "glucose catabolic process",
  "glucose level",
  "glutamate level",
  "glycogen level",
  "glycogen metabolism",
  "growth rate",
  "guanyl-nucleotide exchange factor activity",
  "guanylyl cyclase activity",
  "heterotrimeric G-protein complex assembly",
  "histone deacetylase activity",
  "histone H3K4 methyltransferase activity",
  "histone H3K79 methyltransferase activity",
  "histone H3K9 methyltransferase activity",
  "inner basal disc formation",
  "inner basal disc size",
  "inositol phosphate metabolic process",
  "intermediate filament bundle assembly",
  "intermediate filament organization",
  "intracellular distribution of mitochondria",
  "ion transport",
  "iron ion transport",
  "lateral pseudopodium formation",
  "lateral pseudopodium retraction",
  "late culminant stage",
  "lipid binding",
  "lipid droplet formation",
  "lipid storage",
  "localization",
  "loose mound stage",
  "lower cup formation",
  "lower cup size",
  "lysosomal pH",
  "lysosomal protein degradation",
  "lysosome morphology",
  "lysosome organization",
  "lysosome size",
  "macroautophagy",
  "macrocyst formation",
  "macrocyst morphology",
  "macromolecule biosynthesis",
  "macropinocytosis",
  "mating type determination",
  "membrane ruffling",
  "microtubule cytoskeleton organization",
  "microtubule nucleation",
  "mid culminant stage",
  "migratory slug length",
  "migratory slug size",
  "mitochondrial fission",
  "mitochondrial fusion",
  "mitochondrion morphology",
  "mitochondrion organization",
  "mitotic actomyosin contractile ring contraction",
  "mitotic anaphase",
  "mitotic cell cycle",
  "mitotic sister chromatid segregation",
  "mitotic spindle elongation",
  "mitotic spindle organization",
  "molecular function",
  "mound color",
  "mound size",
  "mound stage",
  "myo-inositol level",
  "myosin II assembly",
  "myosin II filament organization",
  "myosin heavy chain kinase activity",
  "negative chemotaxis",
  "negative regulation of mitochondrial membrane potential",
  "negative regulation of stalk cell differentiation",
  "negative regulation of vegetative growth",
  "nucleus localization",
  "nucleus morphology",
  "nucleus organization",
  "number of astral microtubules",
  "number of autophagosomes",
  "number of centrosomes",
  "number of contractile vacuoles",
  "number of early culminant tips",
  "number of microtubule organizing centers",
  "number of mitochondria",
  "number of mound tips",
  "number of mounds",
  "number of pinosomes",
  "number of post-lysosomal vacuoles",
  "number of tip-organizers",
  "number of vacuoles",
  "organelle localization",
  "organelle morphology",
  "organelle organization",
  "oscillatory cAMP signaling",
  "osmosensory signaling pathway",
  "outer basal disc formation",
  "outer basal disc size",
  "peptidyl-proline 4-dioxygenase activity",
  "phagocytosis",
  "phagolysosome formation",
  "phagolysosome size",
  "phagosome acidification",
  "phagosome maturation",
  "phagosome reneutralization",
  "phosphatase activity",
  "phosphatidylinositol 3-kinase/protein kinase B signal transduction",
  "phosphatidylinositol binding",
  "phosphatidylinositol metabolism",
  "phosphatidylinositol synthesis",
  "phosphatidylinositol-4,5-bisphosphate binding",
  "phototaxis",
  "pinocytosis",
  "pinosome maturation",
  "pinosome size",
  "plasma membrane organization",
  "polyketide metabolic process",
  "polysaccharide binding",
  "pore formation during contractile vacuole discharge",
  "positive chemotaxis",
  "positive regulation of mitochondrial membrane potential",
  "positive regulation of stalk cell differentiation",
  "positive regulation of vegetative growth",
  "post-lysosomal vacuole exocytosis",
  "post-lysosomal vacuole size",
  "pre-miRNA processing",
  "prenylcysteine carboxymethyltransferase activity",
  "prespore cell differentiation",
  "prespore cell division",
  "prespore gene expression",
  "prestalk A cell differentiation",
  "prestalk B cell differentiation",
  "prestalk O cell differentiation",
  "prestalk U cell differentiation",
  "prestalk cell differentiation",
  "prestalk gene expression",
  "programmed cell death",
  "programmed necrotic cell death",
  "proteasomal protein catabolic process",
  "protein binding",
  "protein kinase activity",
  "protein kinase regulator activity",
  "protein level",
  "protein localization",
  "protein localization to actin wave",
  "protein localization to apical plasma membrane",
  "protein localization to autophagosome",
  "protein localization to basolateral plasma membrane",
  "protein localization to cell cortex",
  "protein localization to cell periphery",
  "protein localization to cell surface",
  "protein localization to cell-cell contact zone",
  "protein localization to centrosome",
  "protein localization to clathrin-coated pit",
  "protein localization to cleavage furrow",
  "protein localization to contractile vacuole",
  "protein localization to contractile vacuole membrane",
  "protein localization to cytoplasm",
  "protein localization to cytoplasmic vesicle",
  "protein localization to endolysosome",
  "protein localization to filopodium",
  "protein localization to leading edge",
  "protein localization to lysosomal membrane",
  "protein localization to lysosome",
  "protein localization to macropinosome",
  "protein localization to microtubule organizing center",
  "protein localization to microtubules",
  "protein localization to mitotic actomyosin contractile ring",
  "protein localization to mitotic spindle",
  "protein localization to mitotic spindle midzone",
  "protein localization to nuclear envelope",
  "protein localization to nucleus",
  "protein localization to nucleolus",
  "protein localization to phagocytic vesicle",
  "protein localization to plasma membrane",
  "protein localization to post-lysosomal vacuole",
  "protein localization to pseudopodium",
  "protein localization to trailing edge",
  "protein metabolic process",
  "protein modification",
  "protein secretion",
  "protein stabilization",
  "protein tyrosine kinase activity",
  "protein tyrosine phosphatase activity",
  "pteridine level",
  "rate of endocytosis",
  "regulation of MAPK cascade",
  "regulation of STAT signaling pathway",
  "regulation of intracellular pH",
  "regulation of mitochondrial membrane potential",
  "regulation of positive chemotaxis",
  "regulation of siRNA processing",
  "regulation of vegetative growth",
  "resistance to 5-Fluoroorotic acid",
  "resistance to N-Phenylthiourea",
  "resistance to TMB-8",
  "resistance to alendronic acid",
  "resistance to bleomycin",
  "resistance to carboplatin",
  "resistance to cheating during chimeric sorocarp development",
  "resistance to cisplatin",
  "resistance to hydrogen peroxide",
  "resistance to hydroxyurea",
  "resistance to naringenin",
  "resistance to nocodazole",
  "resistance to phleomycin",
  "resistance to spectinomycin",
  "resistance to valproic acid",
  "response to Gram-negative bacterium",
  "response to Gram-positive bacterium",
  "response to cAMP",
  "response to bacterium",
  "response to biotic stimulus",
  "response to bleomycin",
  "response to chemical",
  "response to cisplatin",
  "response to DIF-1",
  "response to hydroxyurea",
  "response to lithium",
  "response to nocodazole",
  "response to N-Phenylthiourea",
  "response to nutrient",
  "response to oxidative stress",
  "response to stimulus",
  "response to UV",
  "secretion",
  "secretion of lysosomal enzymes",
  "signal transduction",
  "signaling receptor activity",
  "single-strand break repair",
  "size of astral microtubules",
  "slime trail",
  "slug development",
  "slug migration",
  "slug stage",
  "small GTPase-mediated signal transduction",
  "small molecule binding",
  "socially cooperative development",
  "sorocarp development",
  "sorus color",
  "sorus morphology",
  "sorus size",
  "spore cell differentiation",
  "spore coat morphology",
  "spore color",
  "spore germination",
  "spore morphology",
  "spore resistance to hydrogen peroxide",
  "spore size",
  "spore stability",
  "sporulation",
  "stalk cell differentiation",
  "stalk development",
  "stalk length",
  "stalk morphology",
  "stalk width",
  "standing slug length",
  "standing slug morphology",
  "standing slug stage",
  "standing slug width",
  "stream development",
  "substrate adhesion-dependent cell spreading",
  "superoxide generation",
  "taxis",
  "thermotaxis",
  "thymidine biosynthetic process",
  "tipped mound stage",
  "transferase activity",
  "translation",
  "transport",
  "ubiquitin-dependent protein catabolic process",
  "uracil biosynthetic process",
  "uropod retraction",
  "vacuole organization",
  "vegetative cell size",
  "vegetative growth",
  "vesicle coat assembly",
]

const handleSearch = () => {
  // no-op for now — query wiring comes later
}

const SearchPhenotypeForm = () => {
  const [quality, setQuality] = useState("")
  const [entity, setEntity] = useState("")

  const isWildType = quality === "wild type"

  const handleQualityChange = (
    _: SyntheticEvent,
    value: string | null,
    reason: AutocompleteChangeReason,
  ) => {
    match(reason)
      .with("selectOption", () => {
        setQuality(value ?? "")
        if (value === "wild type") setEntity("")
      })
      .with("clear", () => {
        setQuality("")
      })
      .otherwise(() => {})
  }

  const handleEntityChange = (
    _: SyntheticEvent,
    value: string | null,
    reason: AutocompleteChangeReason,
  ) => {
    match(reason)
      .with("selectOption", () => setEntity(value ?? ""))
      .with("clear", () => setEntity(""))
      .otherwise(() => {})
  }

  return (
    <Grid container spacing={2} alignItems="center" justifyContent="center">
      <Grid item xs={12} sm={4}>
        <Autocomplete
          value={quality}
          options={QUALITY_OPTIONS}
          onChange={handleQualityChange}
          renderInput={(parameters) => (
            <TextField
              {...parameters}
              label="Quality"
              size="small"
              variant="outlined"
            />
          )}
        />
      </Grid>
      <Grid item xs={12} sm={6}>
        <Autocomplete
          value={entity}
          options={ENTITY_OPTIONS}
          disabled={isWildType}
          onChange={handleEntityChange}
          renderInput={(parameters) => (
            <TextField
              {...parameters}
              label="Entity"
              size="small"
              variant="outlined"
              helperText={
                isWildType ? "No entity needed for wild type" : undefined
              }
            />
          )}
        />
      </Grid>
      <Grid item xs={12} sm={2}>
        <Button
          variant="contained"
          disabled={!quality || (!isWildType && !entity)}
          onClick={handleSearch}
          fullWidth>
          Search
        </Button>
      </Grid>
    </Grid>
  )
}

export { SearchPhenotypeForm }
