version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    ignore: 
    - dependency-name: "react"
    - dependency-name: "@types/react"
    - dependency-name: "@types/node"
    schedule:
      interval: daily
      time: "16:00"
      timezone: America/Chicago
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    target-branch: develop
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "11:00"
      timezone: America/Chicago
