language: node_js
node_js:
  - "10.4.0"

cache:
  directories:
    - $HOME/.npm

before_script:
  - mv src/common/utils/clientConfig.sample.js src/common/utils/clientConfig.js

script:
  - npm test

# safelist
branches:
  only:
  - master
  - develop
