module.exports = {
  styleguideDir: "styleguide",
  components: "src/**/*.js",
  title: "dictyBase Gene Page",
  ignore: [
    "**/*.test.{js,jsx,ts,tsx}",
    "**/*Actions.js",
    "**/*Constants.js",
    "**/*Reducer.js",
    "**/*Store.js",
    "**/*Styles.js",
    "**/mockData.js",
    "**/panelLabels.js",
    "src/common/constants/*.js",
    "src/common/utils/*.js",
    "src/features/Ontology/utils/*.js",
    "src/features/Ontology/Table/utils/*.js",
    "src/features/ProteinInformation/*.js",
    "src/features/ProteinInformation/Tables/*.js",
    "src/styles/*.js",
    "src/index.js",
    "src/registerServiceWorker.js",
    "src/setupTests.js",
  ],
}
