const INVALID_POSTAL_CODE_MESSAGE =
  "The postal code entered might be invalid for the selected country. Please check the country and postal code fields."

const INVALID_PHONE_MESSAGE =
  "The phone number entered for the shipping information appears to be invalid. Please double-check the phone number and make sure the country code is correct."

const QUALITY_OPTIONS = [
  "aberrant",
  "abolished",
  "decreased",
  "delayed",
  "development arrests at",
  "increased",
  "precocious",
  "wild type",
]

const ENTITY_OPTIONS = [
  "2,3-bisphosphoglycerate level",
  "3',5'-cyclic-AMP phosphodiesterase activity",
  "3',5'-cyclic-GMP phosphodiesterase activity",
  "ATP level",
  "G protein-coupled chemorepellent receptor signaling pathway",
  "G protein-coupled receptor signaling",
  "GABA signaling pathway",
  "GTPase activator activity",
  "GTPase regulator activity",
  "Golgi localization",
  "MPBD level",
  "Rab protein signal transduction",
  "Rac protein signal transduction",
  "Rap protein signal transduction",
  "Ras protein signal transduction",
  "STAT signaling pathway",
  "TORC2 signaling",
  "actin cytoskeleton organization",
  "actin filament bundle assembly",
  "actin filament depolymerization",
  "actin filament organization",
  "actin filament polymerization",
  "actin filament polymerization at leading edge",
  "actin filament sliding",
  "actin nucleation",
  "adaptation of signaling pathway",
  "adenylate cyclase activator activity",
  "adenylate cyclase activity",
  "adenylate cyclase regulator activity",
  "aggregation",
  "aggregation territory size",
  "autophagic cell death",
  "autophagic vacuole organization",
  "autophagosome maturation",
  "autophagosome organization",
  "autophagy",
  "basal disc formation",
  "binding",
  "bleb assembly",
  "cAMP binding",
  "cAMP biosynthesis",
  "cAMP level",
  "cGMP biosynthesis",
  "cGMP-mediated signaling",
  "calcium ion import",
  "calcium-dependent cell-cell adhesion",
  "calcium-independent cell-cell adhesion",
  "calcium-mediated signaling",
  "cell adhesion",
  "cell cycle",
  "cell death",
  "cell differentiation",
  "cell fate determination",
  "cell migration to prestalk region",
  "cell morphogenesis",
  "cell motility",
  "cell motility in response to calcium ion",
  "cell polarity",
  "cell projection biogenesis",
  "cell separation during cytokinesis",
  "cell-cell adhesion",
  "cell-cell recognition",
  "cell-cell self recognition",
  "cell-substrate adhesion",
  "cellular DNA damage response",
  "cellular defense response",
  "cellular homeostasis",
  "cellular hyperosmotic response",
  "cellular hypotonic response",
  "cellular localization",
  "cellular metabolic process",
  "cellular process",
  "cellular response to cation stress",
  "cellular response to extracellular stimulus",
  "cellular response to fluid shear stress",
  "cellular response to heat",
  "cellular response to hypoxia",
  "cellular response to nitrogen starvation",
  "cellular response to osmotic stress",
  "cellular response to starvation",
  "cellular response to stress",
  "cellular thermotolerance",
  "cellulose binding",
  "cellulose biosynthesis",
  "centromere complex assembly",
  "centrosome localization",
  "centrosome organization",
  "cheating during chimeric sorocarp development",
  "chemorepellent activity",
  "chemotaxis",
  "chemotaxis rate",
  "chemotaxis to arachidonic acid",
  "chemotaxis to cAMP",
  "chemotaxis to folate",
  "chromatin assembly",
  "co-transcriptional gene silencing by RNA interference machinery",
  "contractile vacuole discharge",
  "contractile vacuole dissociation from plasma membrane",
  "contractile vacuole localization",
  "contractile vacuole morphology",
  "contractile vacuole organization",
  "contractile vacuole size",
  "contractile vacuole tethering involved in discharge",
  "cortical actin cytoskeleton organization",
  "culmination",
  "cyclic nucleotide binding",
  "cytochrome C oxidase activity",
  "cytokinesis",
  "cytoskeleton organization",
  "cytoplasmic vesicle (protein localization to)",
  "DIF-1 biosynthesis",
  "DNA (cytosine-5-)-methyltransferase activity",
  "DNA repair",
  "DNA-methyltransferase activity",
  "defense response to Gram-negative bacterium",
  "defense response to Gram-positive bacterium",
  "defense response to bacterium",
  "defense response to fungus",
  "double-strand break repair",
  "double-strand break repair via homologous recombination",
  "double-strand break repair via nonhomologous end joining",
  "early culminant stage",
  "endocytic recycling",
  "endocytosis",
  "endolysosome (protein localization to)",
  "endoplasmic reticulum membrane organization",
  "endoplasmic reticulum organization",
  "endosomal transport",
  "endosomal vesicle fusion",
  "endosome morphology",
  "endosome size",
  "engulfment during phagocytosis",
  "epithelium-like organization",
  "establishment of cell polarity",
  "establishment or maintenance of cell polarity",
  "exocytosis",
  "extracellular cAMP signaling pathway",
  "fatty acid level",
  "filopodium formation",
  "folic acid binding",
  "fruiting body morphogenesis",
  "fruiting body size",
  "gene expression",
  "glucose catabolic process",
  "glucose level",
  "glutamate level",
  "glycogen level",
  "glycogen metabolism",
  "growth rate",
  "guanyl-nucleotide exchange factor activity",
  "guanylyl cyclase activity",
  "heterotrimeric G-protein complex assembly",
  "histone deacetylase activity",
  "histone H3K4 methyltransferase activity",
  "histone H3K79 methyltransferase activity",
  "histone H3K9 methyltransferase activity",
  "inner basal disc formation",
  "inner basal disc size",
  "inositol phosphate metabolic process",
  "intermediate filament bundle assembly",
  "intermediate filament organization",
  "intracellular distribution of mitochondria",
  "ion transport",
  "iron ion transport",
  "lateral pseudopodium formation",
  "lateral pseudopodium retraction",
  "late culminant stage",
  "lipid binding",
  "lipid droplet formation",
  "lipid storage",
  "localization",
  "loose mound stage",
  "lower cup formation",
  "lower cup size",
  "lysosomal pH",
  "lysosomal protein degradation",
  "lysosome morphology",
  "lysosome organization",
  "lysosome size",
  "macroautophagy",
  "macrocyst formation",
  "macrocyst morphology",
  "macromolecule biosynthesis",
  "macropinocytosis",
  "mating type determination",
  "membrane ruffling",
  "microtubule cytoskeleton organization",
  "microtubule nucleation",
  "mid culminant stage",
  "migratory slug length",
  "migratory slug size",
  "mitochondrial fission",
  "mitochondrial fusion",
  "mitochondrion morphology",
  "mitochondrion organization",
  "mitotic actomyosin contractile ring contraction",
  "mitotic anaphase",
  "mitotic cell cycle",
  "mitotic sister chromatid segregation",
  "mitotic spindle elongation",
  "mitotic spindle organization",
  "molecular function",
  "mound color",
  "mound size",
  "mound stage",
  "myo-inositol level",
  "myosin II assembly",
  "myosin II filament organization",
  "myosin heavy chain kinase activity",
  "negative chemotaxis",
  "negative regulation of mitochondrial membrane potential",
  "negative regulation of stalk cell differentiation",
  "negative regulation of vegetative growth",
  "nucleus localization",
  "nucleus morphology",
  "nucleus organization",
  "number of astral microtubules",
  "number of autophagosomes",
  "number of centrosomes",
  "number of contractile vacuoles",
  "number of early culminant tips",
  "number of microtubule organizing centers",
  "number of mitochondria",
  "number of mound tips",
  "number of mounds",
  "number of pinosomes",
  "number of post-lysosomal vacuoles",
  "number of tip-organizers",
  "number of vacuoles",
  "organelle localization",
  "organelle morphology",
  "organelle organization",
  "oscillatory cAMP signaling",
  "osmosensory signaling pathway",
  "outer basal disc formation",
  "outer basal disc size",
  "peptidyl-proline 4-dioxygenase activity",
  "phagocytosis",
  "phagolysosome formation",
  "phagolysosome size",
  "phagosome acidification",
  "phagosome maturation",
  "phagosome reneutralization",
  "phosphatase activity",
  "phosphatidylinositol 3-kinase/protein kinase B signal transduction",
  "phosphatidylinositol binding",
  "phosphatidylinositol metabolism",
  "phosphatidylinositol synthesis",
  "phosphatidylinositol-4,5-bisphosphate binding",
  "phototaxis",
  "pinocytosis",
  "pinosome maturation",
  "pinosome size",
  "plasma membrane organization",
  "polyketide metabolic process",
  "polysaccharide binding",
  "pore formation during contractile vacuole discharge",
  "positive chemotaxis",
  "positive regulation of mitochondrial membrane potential",
  "positive regulation of stalk cell differentiation",
  "positive regulation of vegetative growth",
  "post-lysosomal vacuole exocytosis",
  "post-lysosomal vacuole size",
  "pre-miRNA processing",
  "prenylcysteine carboxymethyltransferase activity",
  "prespore cell differentiation",
  "prespore cell division",
  "prespore gene expression",
  "prestalk A cell differentiation",
  "prestalk B cell differentiation",
  "prestalk O cell differentiation",
  "prestalk U cell differentiation",
  "prestalk cell differentiation",
  "prestalk gene expression",
  "programmed cell death",
  "programmed necrotic cell death",
  "proteasomal protein catabolic process",
  "protein binding",
  "protein kinase activity",
  "protein kinase regulator activity",
  "protein level",
  "protein localization",
  "protein localization to actin wave",
  "protein localization to apical plasma membrane",
  "protein localization to autophagosome",
  "protein localization to basolateral plasma membrane",
  "protein localization to cell cortex",
  "protein localization to cell periphery",
  "protein localization to cell surface",
  "protein localization to cell-cell contact zone",
  "protein localization to centrosome",
  "protein localization to clathrin-coated pit",
  "protein localization to cleavage furrow",
  "protein localization to contractile vacuole",
  "protein localization to contractile vacuole membrane",
  "protein localization to cytoplasm",
  "protein localization to cytoplasmic vesicle",
  "protein localization to endolysosome",
  "protein localization to filopodium",
  "protein localization to leading edge",
  "protein localization to lysosomal membrane",
  "protein localization to lysosome",
  "protein localization to macropinosome",
  "protein localization to microtubule organizing center",
  "protein localization to microtubules",
  "protein localization to mitotic actomyosin contractile ring",
  "protein localization to mitotic spindle",
  "protein localization to mitotic spindle midzone",
  "protein localization to nuclear envelope",
  "protein localization to nucleus",
  "protein localization to nucleolus",
  "protein localization to phagocytic vesicle",
  "protein localization to plasma membrane",
  "protein localization to post-lysosomal vacuole",
  "protein localization to pseudopodium",
  "protein localization to trailing edge",
  "protein metabolic process",
  "protein modification",
  "protein secretion",
  "protein stabilization",
  "protein tyrosine kinase activity",
  "protein tyrosine phosphatase activity",
  "pteridine level",
  "rate of endocytosis",
  "regulation of MAPK cascade",
  "regulation of STAT signaling pathway",
  "regulation of intracellular pH",
  "regulation of mitochondrial membrane potential",
  "regulation of positive chemotaxis",
  "regulation of siRNA processing",
  "regulation of vegetative growth",
  "resistance to 5-Fluoroorotic acid",
  "resistance to N-Phenylthiourea",
  "resistance to TMB-8",
  "resistance to alendronic acid",
  "resistance to bleomycin",
  "resistance to carboplatin",
  "resistance to cheating during chimeric sorocarp development",
  "resistance to cisplatin",
  "resistance to hydrogen peroxide",
  "resistance to hydroxyurea",
  "resistance to naringenin",
  "resistance to nocodazole",
  "resistance to phleomycin",
  "resistance to spectinomycin",
  "resistance to valproic acid",
  "response to Gram-negative bacterium",
  "response to Gram-positive bacterium",
  "response to cAMP",
  "response to bacterium",
  "response to biotic stimulus",
  "response to bleomycin",
  "response to chemical",
  "response to cisplatin",
  "response to DIF-1",
  "response to hydroxyurea",
  "response to lithium",
  "response to nocodazole",
  "response to N-Phenylthiourea",
  "response to nutrient",
  "response to oxidative stress",
  "response to stimulus",
  "response to UV",
  "secretion",
  "secretion of lysosomal enzymes",
  "signal transduction",
  "signaling receptor activity",
  "single-strand break repair",
  "size of astral microtubules",
  "slime trail",
  "slug development",
  "slug migration",
  "slug stage",
  "small GTPase-mediated signal transduction",
  "small molecule binding",
  "socially cooperative development",
  "sorocarp development",
  "sorus color",
  "sorus morphology",
  "sorus size",
  "spore cell differentiation",
  "spore coat morphology",
  "spore color",
  "spore germination",
  "spore morphology",
  "spore resistance to hydrogen peroxide",
  "spore size",
  "spore stability",
  "sporulation",
  "stalk cell differentiation",
  "stalk development",
  "stalk length",
  "stalk morphology",
  "stalk width",
  "standing slug length",
  "standing slug morphology",
  "standing slug stage",
  "standing slug width",
  "stream development",
  "substrate adhesion-dependent cell spreading",
  "superoxide generation",
  "taxis",
  "thermotaxis",
  "thymidine biosynthetic process",
  "tipped mound stage",
  "transferase activity",
  "translation",
  "transport",
  "ubiquitin-dependent protein catabolic process",
  "uracil biosynthetic process",
  "uropod retraction",
  "vacuole organization",
  "vegetative cell size",
  "vegetative growth",
  "vesicle coat assembly",
]

const PHENOTYPE_OPTIONS = [
  "aberrant actin cytoskeleton organization",
  "aberrant actin filament depolymerization",
  "aberrant actin filament organization",
  "aberrant actin filament polymerization",
  "aberrant adaptation of signaling pathway",
  "aberrant adenylate cyclase activator activity",
  "aberrant adenylate cyclase regulator activity",
  "aberrant aggregation",
  "aberrant aggregation territory size",
  "aberrant autophagic cell death",
  "aberrant autophagosome maturation",
  "aberrant autophagy",
  "aberrant basal disc formation",
  "aberrant binding",
  "aberrant bleb assembly",
  "aberrant calcium-mediated signaling",
  "aberrant cAMP level",
  "aberrant catalase activity",
  "aberrant catalytic activity",
  "aberrant cell adhesion",
  "aberrant cell-cell adhesion",
  "aberrant cell-cell recognition",
  "aberrant cell-cell self recognition",
  "aberrant cell cycle",
  "aberrant cell death",
  "aberrant cell differentiation",
  "aberrant cell fate determination",
  "aberrant cell migration to prestalk region",
  "aberrant cell morphogenesis",
  "aberrant cell motility",
  "aberrant cell motility in response to calcium ion",
  "aberrant cell projection biogenesis",
  "aberrant cell separation during cytokinesis",
  "aberrant cell-substrate adhesion",
  "aberrant cellular component organization",
  "aberrant cellular defense response",
  "aberrant cellular DNA damage response",
  "aberrant cellular homeostasis",
  "aberrant cellular hyperosmotic response",
  "aberrant cellular hypotonic response",
  "aberrant cellular localization",
  "aberrant cellular metabolic process",
  "aberrant cellular process",
  "aberrant cellular response to cation stress",
  "aberrant cellular response to extracellular stimulus",
  "aberrant cellular response to fluid shear stress",
  "aberrant cellular response to heat",
  "aberrant cellular response to hypoxia",
  "aberrant cellular response to nitrogen starvation",
  "aberrant cellular response to osmotic stress",
  "aberrant cellular response to starvation",
  "aberrant cellular response to stress",
  "aberrant cellulose binding",
  "aberrant cellulose biosynthesis",
  "aberrant centromere complex assembly",
  "aberrant centrosome localization",
  "aberrant centrosome organization",
  "aberrant cGMP-mediated signaling",
  "aberrant cheating during chimeric sorocarp development",
  "aberrant chemorepellent activity",
  "aberrant chemotaxis",
  "aberrant chemotaxis to cAMP",
  "aberrant chemotaxis to folate",
  "aberrant chromatin assembly",
  "aberrant contractile vacuole discharge",
  "aberrant contractile vacuole dissociation from plasma membrane",
  "aberrant contractile vacuole localization",
  "aberrant contractile vacuole morphology",
  "aberrant contractile vacuole organization",
  "aberrant contractile vacuole tethering involved in discharge",
  "aberrant cortical actin cytoskeleton organization",
  "aberrant co-transcriptional gene silencing by RNA interference machinery",
  "aberrant culmination",
  "aberrant cyclic nucleotide binding",
  "aberrant cytokinesis",
  "aberrant cytoskeleton organization",
  "aberrant defense response to bacterium",
  "aberrant defense response to fungus",
  "aberrant defense response to Gram-negative bacterium",
  "aberrant defense response to Gram-positive bacterium",
  "aberrant development of tipped mound",
  "aberrant DIF-1 biosynthesis",
  "aberrant DNA (cytosine-5-)-methyltransferase activity",
  "aberrant DNA-methyltransferase activity",
  "aberrant DNA repair",
  "aberrant double-strand break repair",
  "aberrant double-strand break repair via homologous recombination",
  "aberrant double-strand break repair via nonhomologous end joining",
  "aberrant endocytic recycling",
  "aberrant endocytosis",
  "aberrant endoplasmic reticulum membrane organization",
  "aberrant endoplasmic reticulum organization",
  "aberrant endosomal transport",
  "aberrant endosomal vesicle fusion",
  "aberrant endosome morphology",
  "aberrant engulfment during phagocytosis",
  "aberrant epithelium-like organization",
  "aberrant establishment or maintenance of cell polarity",
  "aberrant exocytosis",
  "aberrant extracellular cAMP signaling pathway",
  "aberrant filopodium formation",
  "aberrant folic acid binding",
  "aberrant fruiting body morphogenesis",
  "aberrant GABA signaling pathway",
  "aberrant gene expression",
  "aberrant glucose catabolic process",
  "aberrant glycogen metabolism",
  "aberrant Golgi localization",
  "aberrant G protein-coupled chemorepellent receptor signaling pathway",
  "aberrant G protein-coupled receptor signaling",
  "aberrant GTPase activator activity",
  "aberrant GTPase regulator activity",
  "aberrant heterotrimeric G-protein complex assembly",
  "aberrant histone H3K4 methyltransferase activity",
  "aberrant histone H3K79 methyltransferase activity",
  "aberrant histone H3K9 methyltransferase activity",
  "aberrant inner basal disc formation",
  "aberrant inositol phosphate metabolic process",
  "aberrant intermediate filament bundle assembly",
  "aberrant intermediate filament organization",
  "aberrant intracellular distribution of mitochondria",
  "aberrant ion transport",
  "aberrant late culminant morphology",
  "aberrant lateral pseudopodium formation",
  "aberrant lipid binding",
  "aberrant lipid droplet formation",
  "aberrant lipid storage",
  "aberrant localization",
  "aberrant lower cup formation",
  "aberrant lysosome morphology",
  "aberrant lysosome organization",
  "aberrant macroautophagy",
  "aberrant macrocyst formation",
  "aberrant macrocyst morphology",
  "aberrant macromolecule biosynthesis",
  "aberrant macropinocytosis",
  "aberrant mating type determination",
  "aberrant membrane ruffling",
  "aberrant microtubule cytoskeleton organization",
  "aberrant microtubule nucleation",
  "aberrant mitochondrial fission",
  "aberrant mitochondrial fusion",
  "aberrant mitochondrion morphology",
  "aberrant mitochondrion organization",
  "aberrant mitosis",
  "aberrant mitotic actomyosin contractile ring contraction",
  "aberrant mitotic anaphase",
  "aberrant mitotic sister chromatid segregation",
  "aberrant mitotic spindle elongation",
  "aberrant mitotic spindle organization",
  "aberrant molecular function",
  "aberrant molecular function regulator activity",
  "aberrant mound color",
  "aberrant mound size",
  "aberrant MPBD level",
  "aberrant myosin heavy chain kinase activity",
  "aberrant myosin II filament organization",
  "aberrant negative chemotaxis",
  "aberrant negative regulation of mitochondrial membrane potential",
  "aberrant negative regulation of stalk cell differentiation",
  "aberrant negative regulation of vegetative growth",
  "aberrant nuclear envelope morphology",
  "aberrant nuclear membrane organization",
  "aberrant nucleus localization",
  "aberrant nucleus morphology",
  "aberrant nucleus organization",
  "aberrant organelle localization",
  "aberrant organelle morphology",
  "aberrant organelle organization",
  "aberrant oscillatory cAMP signaling",
  "aberrant osmosensory signaling pathway",
  "aberrant outer basal disc formation",
  "aberrant peptidyl-proline 4-dioxygenase activity",
  "aberrant phagocytosis",
  "aberrant phagolysosome formation",
  "aberrant phagosome maturation",
  "aberrant phosphatase activity",
  "aberrant phosphatidylinositol 3-kinase/protein kinase B signal transduction",
  "aberrant phosphatidylinositol metabolism",
  "aberrant phosphatidylinositol synthesis",
  "aberrant phototaxis",
  "aberrant pinocytosis",
  "aberrant pinosome maturation",
  "aberrant plasma membrane organization",
  "aberrant polyketide metabolic process",
  "aberrant polysaccharide binding",
  "aberrant pore formation during contractile vacuole discharge",
  "aberrant positive chemotaxis",
  "aberrant positive regulation of mitochondrial membrane potential",
  "aberrant positive regulation of stalk cell differentiation",
  "aberrant positive regulation of vegetative growth",
  "aberrant post-lysosomal vacuole exocytosis",
  "aberrant pre-miRNA processing",
  "aberrant prenylcysteine carboxymethyltransferase activity",
  "aberrant prespore cell differentiation",
  "aberrant prespore gene expression",
  "aberrant prestalk A cell differentiation",
  "aberrant prestalk B cell differentiation",
  "aberrant prestalk cell differentiation",
  "aberrant prestalk gene expression",
  "aberrant prestalk O cell differentiation",
  "aberrant prestalk U cell differentiation",
  "aberrant programmed cell death",
  "aberrant programmed necrotic cell death",
  "aberrant proteasomal protein catabolic process",
  "aberrant protein binding",
  "aberrant protein-containing complex assembly",
  "aberrant protein kinase activity",
  "aberrant protein kinase regulator activity",
  "aberrant protein level",
  "aberrant protein localization",
  "aberrant protein localization to actin wave",
  "aberrant protein localization to apical plasma membrane",
  "aberrant protein localization to autophagosome",
  "aberrant protein localization to basolateral plasma membrane",
  "aberrant protein localization to cell-cell contact zone",
  "aberrant protein localization to cell cortex",
  "aberrant protein localization to cell periphery",
  "aberrant protein localization to cell surface",
  "aberrant protein localization to centrosome",
  "aberrant protein localization to clathrin-coated pit",
  "aberrant protein localization to cleavage furrow",
  "aberrant protein localization to contractile vacuole",
  "aberrant protein localization to contractile vacuole membrane",
  "aberrant protein localization to cytoplasm",
  "aberrant protein localization to cytoplasmic vesicle",
  "aberrant protein localization to endolysosome",
  "aberrant protein localization to filopodium",
  "aberrant protein localization to leading edge",
  "aberrant protein localization to lysosomal membrane",
  "aberrant protein localization to lysosome",
  "aberrant protein localization to macropinosome",
  "aberrant protein localization to microtubule organizing center",
  "aberrant protein localization to microtubules",
  "aberrant protein localization to mitotic actomyosin contractile ring",
  "aberrant protein localization to mitotic spindle",
  "aberrant protein localization to mitotic spindle midzone",
  "aberrant protein localization to nuclear envelope",
  "aberrant protein localization to nucleolus",
  "aberrant protein localization to nucleus",
  "aberrant protein localization to phagocytic vesicle",
  "aberrant protein localization to plasma membrane",
  "aberrant protein localization to post-lysosomal vacuole",
  "aberrant protein localization to pseudopodium",
  "aberrant protein localization to trailing edge",
  "aberrant protein metabolic process",
  "aberrant protein modification",
  "aberrant protein secretion",
  "aberrant protein stabilization",
  "aberrant protein tyrosine kinase activity",
  "aberrant protein tyrosine phosphatase activity",
  "aberrant pseudopodium formation",
  "aberrant Rab protein signal transduction",
  "aberrant Rac protein signal transduction",
  "aberrant Rap protein signal transduction",
  "aberrant Ras protein signal transduction",
  "aberrant regulation of fruiting body formation",
  "aberrant regulation of intracellular pH",
  "aberrant regulation of MAPK cascade",
  "aberrant regulation of mitochondrial membrane potential",
  "aberrant regulation of positive chemotaxis",
  "aberrant regulation of protein modification",
  "aberrant regulation of siRNA processing",
  "aberrant regulation of stalk cell differentiation",
  "aberrant regulation of STAT signaling pathway",
  "aberrant regulation of vegetative growth",
  "aberrant response to abiotic stimulus",
  "aberrant response to bacterium",
  "aberrant response to biotic stimulus",
  "aberrant response to bleomycin",
  "aberrant response to cAMP",
  "aberrant response to chemical",
  "aberrant response to cisplatin",
  "aberrant response to DIF-1",
  "aberrant response to hydroxyurea",
  "aberrant response to lithium",
  "aberrant response to nocodazole",
  "aberrant response to N-Phenylthiourea",
  "aberrant response to nutrient",
  "aberrant response to oxidative stress",
  "aberrant response to stimulus",
  "aberrant response to UV",
  "aberrant secretion",
  "aberrant signaling receptor activity",
  "aberrant signal transduction",
  "aberrant single-strand break repair",
  "aberrant slug development",
  "aberrant slug migration",
  "aberrant small GTPase-mediated signal transduction",
  "aberrant small molecule binding",
  "aberrant socially cooperative development",
  "aberrant sorocarp development",
  "aberrant sorus color",
  "aberrant sorus morphology",
  "aberrant spore cell differentiation",
  "aberrant spore coat morphology",
  "aberrant spore color",
  "aberrant spore germination",
  "aberrant spore morphology",
  "aberrant sporulation",
  "aberrant stalk cell differentiation",
  "aberrant stalk development",
  "aberrant stalk morphology",
  "aberrant standing slug morphology",
  "aberrant STAT signaling pathway",
  "aberrant stream development",
  "aberrant substrate adhesion-dependent cell spreading",
  "aberrant taxis",
  "aberrant thermotaxis",
  "aberrant TORC2 signaling",
  "aberrant transferase activity",
  "aberrant transitive RNA interference",
  "aberrant translation",
  "aberrant transport",
  "aberrant ubiquitin-dependent protein catabolic process",
  "aberrant upper cup formation",
  "aberrant vacuole organization",
  "aberrant vegetative growth",
  "aberrant vesicle coat assembly",
  "abolished 3',5'-cyclic-AMP phosphodiesterase activity",
  "abolished 3',5'-cyclic-GMP phosphodiesterase activity",
  "abolished actin filament depolymerization",
  "abolished actin filament polymerization",
  "abolished adenylate cyclase activator activity",
  "abolished adenylate cyclase activity",
  "abolished adenylate cyclase regulator activity",
  "abolished aggregation",
  "abolished autophagic cell death",
  "abolished autophagosome maturation",
  "abolished autophagosome organization",
  "abolished basal disc formation",
  "abolished bleb assembly",
  "abolished calcium-dependent cell-cell adhesion",
  "abolished calcium-independent cell-cell adhesion",
  "abolished cAMP binding",
  "abolished cAMP biosynthesis",
  "abolished catalase activity",
  "abolished catalytic activity",
  "abolished cell-cell adhesion",
  "abolished cell-cell self recognition",
  "abolished cell differentiation",
  "abolished cell migration to prestalk region",
  "abolished cell motility",
  "abolished cell motility in response to calcium ion",
  "abolished cell-substrate adhesion",
  "abolished cellular DNA damage response",
  "abolished cellular hypotonic response",
  "abolished cellular localization",
  "abolished cellulose binding",
  "abolished cellulose biosynthesis",
  "abolished cGMP-mediated signaling",
  "abolished chemorepellent activity",
  "abolished chemotaxis to cAMP",
  "abolished chemotaxis to folate",
  "abolished contractile vacuole discharge",
  "abolished contractile vacuole dissociation from plasma membrane",
  "abolished contractile vacuole organization",
  "abolished contractile vacuole tethering involved in discharge",
  "abolished co-transcriptional gene silencing by RNA interference machinery",
  "abolished culmination",
  "abolished cytochrome C oxidase activity",
  "abolished cytokinesis",
  "abolished defense response to bacterium",
  "abolished defense response to Gram-negative bacterium",
  "abolished defense response to Gram-positive bacterium",
  "abolished development of tipped mound",
  "abolished DIF-1 biosynthesis",
  "abolished DNA (cytosine-5-)-methyltransferase activity",
  "abolished double strand break repair",
  "abolished double-strand break repair via homologous recombination",
  "abolished double-strand break repair via nonhomologous end joining",
  "abolished endocytic recycling",
  "abolished engulfment during phagocytosis",
  "abolished epithelium-like organization",
  "abolished establishment of cell polarity",
  "abolished exocytosis",
  "abolished filopodium formation",
  "abolished folic acid binding",
  "abolished gene expression",
  "abolished G protein-coupled chemorepellent receptor signaling pathway",
  "abolished GTPase activator activity",
  "abolished guanyl-nucleotide exchange factor activity",
  "abolished guanylyl cyclase activity",
  "abolished heterotrimeric G-protein complex assembly",
  "abolished histone deacetylase activity",
  "abolished histone H3K4 methyltransferase activity",
  "abolished histone H3K79 methyltransferase activity",
  "abolished histone H3K9 methyltransferase activity",
  "abolished inner basal disc formation",
  "abolished iron ion transport",
  "abolished lipid binding",
  "abolished lipid droplet formation",
  "abolished lower cup formation",
  "abolished lysosomal protein degradation",
  "abolished macroautophagy",
  "abolished macropinocytosis",
  "abolished mating type determination",
  "abolished MPBD level",
  "abolished myosin heavy chain kinase activity",
  "abolished negative chemotaxis",
  "abolished negative regulation of vegetative growth",
  "abolished oscillatory cAMP signaling",
  "abolished outer basal disc formation",
  "abolished peptidyl-proline 4-dioxygenase activity",
  "abolished phagocytosis",
  "abolished phagosome acidification",
  "abolished phagosome reneutralization",
  "abolished phosphatase activity",
  "abolished phosphatidylinositol 3-kinase/protein kinase B signal transduction",
  "abolished phosphatidylinositol-4,5-bisphosphate binding",
  "abolished phosphatidylinositol binding",
  "abolished phosphatidylinositol synthesis",
  "abolished phototaxis",
  "abolished pinocytosis",
  "abolished polyketide metabolic process",
  "abolished pore formation during contractile vacuole discharge",
  "abolished positive chemotaxis",
  "abolished positive regulation of vegetative growth",
  "abolished pre-miRNA processing",
  "abolished prenylcysteine carboxymethyltransferase activity",
  "abolished prespore cell differentiation",
  "abolished prespore cell division",
  "abolished prespore gene expression",
  "abolished prestalk A cell differentiation",
  "abolished prestalk B cell differentiation",
  "abolished prestalk cell differentiation",
  "abolished prestalk gene expression",
  "abolished prestalk O cell differentiation",
  "abolished prestalk U cell differentiation",
  "abolished programmed cell death",
  "abolished programmed necrotic cell death",
  "abolished proteasomal protein catabolic process",
  "abolished protein binding",
  "abolished protein kinase activity",
  "abolished protein kinase regulator activity",
  "abolished protein level",
  "abolished protein localization",
  "abolished protein localization to actin wave",
  "abolished protein localization to apical plasma membrane",
  "abolished protein localization to autophagosome",
  "abolished protein localization to basolateral plasma membrane",
  "abolished protein localization to cell-cell contact zone",
  "abolished protein localization to cell cortex",
  "abolished protein localization to cell periphery",
  "abolished protein localization to cell surface",
  "abolished protein localization to centrosome",
  "abolished protein localization to clathrin-coated pit",
  "abolished protein localization to cleavage furrow",
  "abolished protein localization to contractile vacuole",
  "abolished protein localization to contractile vacuole membrane",
  "abolished protein localization to cytoplasm",
  "abolished protein localization to cytoplasmic vesicle",
  "abolished protein localization to endolysosome",
  "abolished protein localization to filopodium",
  "abolished protein localization to leading edge",
  "abolished protein localization to lysosomal membrane",
  "abolished protein localization to lysosome",
  "abolished protein localization to macropinosome",
  "abolished protein localization to microtubule organizing center",
  "abolished protein localization to microtubules",
  "abolished protein localization to mitotic actomyosin contractile ring",
  "abolished protein localization to mitotic spindle",
  "abolished protein localization to mitotic spindle midzone",
  "abolished protein localization to nuclear envelope",
  "abolished protein localization to nucleolus",
  "abolished protein localization to nucleus",
  "abolished protein localization to phagocytic vesicle",
  "abolished protein localization to plasma membrane",
  "abolished protein localization to post-lysosomal vacuole",
  "abolished protein localization to pseudopodium",
  "abolished protein localization to trailing edge",
  "abolished protein modification",
  "abolished protein secretion",
  "abolished protein stabilization",
  "abolished protein tyrosine kinase activity",
  "abolished protein tyrosine phosphatase activity",
  "abolished Rab protein signal transduction",
  "abolished Rac protein signal transduction",
  "abolished Rap protein signal transduction",
  "abolished Ras protein signal transduction",
  "abolished regulation of MAPK cascade",
  "abolished regulation of siRNA processing",
  "abolished regulation of STAT signaling pathway",
  "abolished response to bacterium",
  "abolished response to biotic stimulus",
  "abolished response to cAMP",
  "abolished response to DIF-1",
  "abolished response to Gram-negative bacterium",
  "abolished response to Gram-positive bacterium",
  "abolished secretion of lysosomal enzymes",
  "abolished single-strand break repair",
  "abolished slug development",
  "abolished slug migration",
  "abolished small GTPase-mediated signal transduction",
  "abolished small molecule binding",
  "abolished spore cell differentiation",
  "abolished sporulation",
  "abolished stalk cell differentiation",
  "abolished stalk development",
  "abolished STAT signaling pathway",
  "abolished stream development",
  "abolished substrate adhesion-dependent cell spreading",
  "abolished superoxide generation",
  "abolished taxis",
  "abolished thermotaxis",
  "abolished thymidine biosynthetic process",
  "abolished TORC2 signaling",
  "abolished transitive RNA interference",
  "abolished translation",
  "abolished ubiquitin-dependent protein catabolic process",
  "abolished upper cup formation",
  "abolished uracil biosynthetic process",
  "abolished vacuole organization",
  "abolished vegetative growth",
  "decreased 2,3-bisphosphoglycerate level",
  "decreased 3',5'-cyclic-AMP phosphodiesterase activity",
  "decreased 3',5'-cyclic-GMP phosphodiesterase activity",
  "decreased actin filament bundle assembly",
  "decreased actin filament depolymerization",
  "decreased actin filament polymerization",
  "decreased actin filament polymerization at leading edge",
  "decreased actin filament sliding",
  "decreased actin nucleation",
  "decreased adenylate cyclase activator activity",
  "decreased adenylate cyclase activity",
  "decreased adenylate cyclase regulator activity",
  "decreased aggregation territory size",
  "decreased ammonia level",
  "decreased ATP level",
  "decreased autophagic cell death",
  "decreased autophagic vacuole organization",
  "decreased autophagosome maturation",
  "decreased autophagy",
  "decreased basal disc size",
  "decreased bleb assembly",
  "decreased calcium-dependent cell-cell adhesion",
  "decreased calcium-independent cell-cell adhesion",
  "decreased calcium ion import",
  "decreased cAMP binding",
  "decreased cAMP biosynthesis",
  "decreased cAMP level",
  "decreased catalase activity",
  "decreased catalytic activity",
  "decreased cell-cell adhesion",
  "decreased cell-cell self recognition",
  "decreased cell death",
  "decreased cell differentiation",
  "decreased cell fate determination",
  "decreased cell migration to prestalk region",
  "decreased cell motility",
  "decreased cell-substrate adhesion",
  "decreased cellular DNA damage response",
  "decreased cellular hypotonic response",
  "decreased cellular localization",
  "decreased cellular response to hypoxia",
  "decreased cellular thermotolerance",
  "decreased cellulose binding",
  "decreased cellulose biosynthesis",
  "decreased cGMP biosynthesis",
  "decreased cGMP-mediated signaling",
  "decreased chemorepellent activity",
  "decreased chemotaxis rate",
  "decreased chemotaxis to arachidonic acid",
  "decreased chemotaxis to cAMP",
  "decreased chemotaxis to folate",
  "decreased contractile vacuole discharge",
  "decreased contractile vacuole size",
  "decreased co-transcriptional gene silencing by RNA interference machinery",
  "decreased culmination",
  "decreased cytochrome C oxidase activity",
  "decreased defense response to bacterium",
  "decreased defense response to fungus",
  "decreased defense response to Gram-negative bacterium",
  "decreased defense response to Gram-positive bacterium",
  "decreased DIF-1 biosynthesis",
  "decreased DNA (cytosine-5-)-methyltransferase activity",
  "decreased DNA-methyltransferase activity",
  "decreased double-strand break repair",
  "decreased double-strand break repair via homologous recombination",
  "decreased double-strand break repair via nonhomologous end joining",
  "decreased endocytic recycling",
  "decreased endosomal vesicle fusion",
  "decreased endosome size",
  "decreased engulfment during phagocytosis",
  "decreased epithelium-like organization",
  "decreased establishment of cell polarity",
  "decreased exocytosis",
  "decreased fatty acid level",
  "decreased filopodium formation",
  "decreased folic acid binding",
  "decreased fruiting body size",
  "decreased gene expression",
  "decreased glucose level",
  "decreased glycogen level",
  "decreased G protein-coupled chemorepellent receptor signaling pathway",
  "decreased growth rate",
  "decreased GTPase activator activity",
  "decreased guanyl-nucleotide exchange factor activity",
  "decreased guanylyl cyclase activity",
  "decreased heterotrimeric G-protein complex assembly",
  "decreased histone deacetylase activity",
  "decreased inner basal disc size",
  "decreased intermediate filament bundle assembly",
  "decreased lateral pseudopodium formation",
  "decreased lateral pseudopodium retraction",
  "decreased lipid binding",
  "decreased lipid droplet formation",
  "decreased lower cup size",
  "decreased lysosomal protein degradation",
  "decreased lysosome size",
  "decreased macroautophagy",
  "decreased macrocyst size",
  "decreased macropinocytosis",
  "decreased membrane ruffling",
  "decreased microtubule nucleation",
  "decreased migratory slug size",
  "decreased mitochondrial fission",
  "decreased mitochondrial fusion",
  "decreased mound size",
  "decreased MPBD level",
  "decreased myo-inositol level",
  "decreased myosin II assembly",
  "decreased negative chemotaxis",
  "decreased number of astral microtubules",
  "decreased number of autophagosomes",
  "decreased number of mitochondria",
  "decreased number of mounds",
  "decreased number of post-lysosomal vacuoles",
  "decreased number of vacuoles",
  "decreased oscillatory cAMP signaling",
  "decreased outer basal disc size",
  "decreased peptidyl-proline 4-dioxygenase activity",
  "decreased phagocytosis",
  "decreased phagolysosome formation",
  "decreased phagolysosome size",
  "decreased phosphatase activity",
  "decreased phosphatidylinositol 3-kinase/protein kinase B signal transduction",
  "decreased phosphatidylinositol synthesis",
  "decreased phototaxis",
  "decreased pinocytosis",
  "decreased pinosome size",
  "decreased plasma membrane organization",
  "decreased post-lysosomal vacuole size",
  "decreased pre-miRNA processing",
  "decreased prespore cell differentiation",
  "decreased prespore gene expression",
  "decreased prestalk A cell differentiation",
  "decreased prestalk B cell differentiation",
  "decreased prestalk cell differentiation",
  "decreased prestalk gene expression",
  "decreased prestalk O cell differentiation",
  "decreased prestalk U cell differentiation",
  "decreased programmed cell death",
  "decreased programmed necrotic cell death",
  "decreased proteasomal protein catabolic process",
  "decreased protein binding",
  "decreased protein kinase activity",
  "decreased protein kinase regulator activity",
  "decreased protein level",
  "decreased protein localization",
  "decreased protein localization to actin wave",
  "decreased protein localization to autophagosome",
  "decreased protein localization to basolateral plasma membrane",
  "decreased protein localization to cell-cell contact zone",
  "decreased protein localization to cell cortex",
  "decreased protein localization to cell surface",
  "decreased protein localization to centrosome",
  "decreased protein localization to clathrin-coated pit",
  "decreased protein localization to cleavage furrow",
  "decreased protein localization to contractile vacuole",
  "decreased protein localization to contractile vacuole membrane",
  "decreased protein localization to cytoplasm",
  "decreased protein localization to cytoplasmic vesicle",
  "decreased protein localization to endolysosome",
  "decreased protein localization to filopodium",
  "decreased protein localization to leading edge",
  "decreased protein localization to lysosomal membrane",
  "decreased protein localization to lysosome",
  "decreased protein localization to macropinosome",
  "decreased protein localization to microtubule organizing center",
  "decreased protein localization to microtubules",
  "decreased protein localization to mitotic actomyosin contractile ring",
  "decreased protein localization to mitotic spindle",
  "decreased protein localization to mitotic spindle midzone",
  "decreased protein localization to nuclear envelope",
  "decreased protein localization to nucleolus",
  "decreased protein localization to nucleus",
  "decreased protein localization to phagocytic vesicle",
  "decreased protein localization to plasma membrane",
  "decreased protein localization to post-lysosomal vacuole",
  "decreased protein localization to pseudopodium",
  "decreased protein localization to trailing edge",
  "decreased protein modification",
  "decreased protein processing in phagocytic vesicle",
  "decreased protein secretion",
  "decreased protein stabilization",
  "decreased protein tyrosine kinase activity",
  "decreased protein tyrosine phosphatase activity",
  "decreased pseudopodium formation",
  "decreased pseudopodium retraction",
  "decreased pseudopodium size",
  "decreased pteridine level",
  "decreased Rab protein signal transduction",
  "decreased Rac protein signal transduction",
  "decreased Rap protein signal transduction",
  "decreased Ras protein signal transduction",
  "decreased rate of endocytosis",
  "decreased regulation of intracellular pH",
  "decreased regulation of MAPK cascade",
  "decreased regulation of siRNA processing",
  "decreased regulation of STAT signaling pathway",
  "decreased resistance to bleomycin",
  "decreased resistance to carboplatin",
  "decreased resistance to cheating during chimeric sorocarp development",
  "decreased resistance to cisplatin",
  "decreased resistance to hydrogen peroxide",
  "decreased resistance to hydroxyurea",
  "decreased resistance to nocodazole",
  "decreased resistance to phleomycin",
  "decreased resistance to TMB-8",
  "decreased response to bacterium",
  "decreased response to cAMP",
  "decreased response to DIF-1",
  "decreased response to Gram-negative bacterium",
  "decreased response to Gram-positive bacterium",
  "decreased response to lithium",
  "decreased secretion of lysosomal enzymes",
  "decreased sexual fusion",
  "decreased single-strand break repair",
  "decreased size of astral microtubules",
  "decreased slime trail",
  "decreased slug migration",
  "decreased small GTPase-mediated signal transduction",
  "decreased small molecule binding",
  "decreased socially cooperative development",
  "decreased sorus size",
  "decreased spore cell differentiation",
  "decreased spore germination",
  "decreased spore resistance to hydrogen peroxide",
  "decreased spore size",
  "decreased spore stability",
  "decreased sporulation",
  "decreased stalk cell differentiation",
  "decreased stalk length",
  "decreased stalk width",
  "decreased standing slug width",
  "decreased substrate adhesion-dependent cell spreading",
  "decreased superoxide generation",
  "decreased taxis",
  "decreased thermotaxis",
  "decreased TORC2 signaling",
  "decreased translation",
  "decreased ubiquitin-dependent protein catabolic process",
  "decreased upper cup size",
  "decreased uropod retraction",
  "decreased vegetative cell size",
  "delayed aggregation",
  "delayed cell separation during cytokinesis",
  "delayed cellular hyperosmotic response",
  "delayed cellular hypotonic response",
  "delayed culmination",
  "delayed cytokinesis",
  "delayed development",
  "delayed development of tipped mound",
  "delayed gene expression",
  "delayed mitotic cell cycle",
  "delayed mitotic spindle elongation",
  "delayed phagosome acidification",
  "delayed phagosome reneutralization",
  "delayed prespore gene expression",
  "delayed prestalk gene expression",
  "delayed pseudopodium formation",
  "delayed response to cAMP",
  "delayed response to DIF-1",
  "delayed slug development",
  "delayed sporulation",
  "development arrests at early culminant stage",
  "development arrests at late culminant stage",
  "development arrests at loose mound stage",
  "development arrests at mid culminant stage",
  "development arrests at mound stage",
  "development arrests at slug stage",
  "development arrests at standing slug stage",
  "development arrests at tipped mound stage",
  "Dicty Phenotypes",
  "increased 2,3-bisphosphoglycerate level",
  "increased 3',5'-cyclic-AMP phosphodiesterase activity",
  "increased 3',5'-cyclic-GMP phosphodiesterase activity",
  "increased actin filament bundle assembly",
  "increased actin filament depolymerization",
  "increased actin filament polymerization",
  "increased actin filament polymerization at leading edge",
  "increased actin filament sliding",
  "increased adenylate cyclase activity",
  "increased aggregation territory size",
  "increased ammonia level",
  "increased ATP level",
  "increased autophagic cell death",
  "increased autophagy",
  "increased basal disc size",
  "increased bleb assembly",
  "increased calcium-dependent cell-cell adhesion",
  "increased calcium-independent cell-cell adhesion",
  "increased cAMP binding",
  "increased cAMP biosynthesis",
  "increased cAMP level",
  "increased catalase activity",
  "increased catalytic activity",
  "increased cell-cell adhesion",
  "increased cell death",
  "increased cell differentiation",
  "increased cell migration to prestalk region",
  "increased cell motility",
  "increased cell-substrate adhesion",
  "increased cellular DNA damage response",
  "increased cellular hypotonic response",
  "increased cellular localization",
  "increased cellular response to hypoxia",
  "increased cellular thermotolerance",
  "increased cellulose biosynthesis",
  "increased cGMP biosynthesis",
  "increased cGMP-mediated signaling",
  "increased chemorepellent activity",
  "increased chemotaxis rate",
  "increased chemotaxis to arachidonic acid",
  "increased chemotaxis to cAMP",
  "increased chemotaxis to folate",
  "increased contractile vacuole discharge",
  "increased contractile vacuole size",
  "increased co-transcriptional gene silencing by RNA interference machinery",
  "increased culmination",
  "increased cytochrome C oxidase activity",
  "increased defense response to bacterium",
  "increased defense response to fungus",
  "increased defense response to Gram-negative bacterium",
  "increased defense response to Gram-positive bacterium",
  "increased DIF-1 biosynthesis",
  "increased double-strand break repair",
  "increased double-strand break repair via homologous recombination",
  "increased double-strand break repair via nonhomologous end joining",
  "increased endocytic recycling",
  "increased endosomal vesicle fusion",
  "increased endosome size",
  "increased establishment of cell polarity",
  "increased exocytosis",
  "increased filopodium formation",
  "increased folic acid binding",
  "increased fruiting body size",
  "increased gene expression",
  "increased glucose level",
  "increased glutamate level",
  "increased glycogen level",
  "increased G protein-coupled chemorepellent receptor signaling pathway",
  "increased growth rate",
  "increased GTPase activator activity",
  "increased guanyl-nucleotide exchange factor activity",
  "increased guanylyl cyclase activity",
  "increased heterotrimeric G-protein complex assembly",
  "increased histone deacetylase activity",
  "increased inner basal disc size",
  "increased intermediate filament bundle assembly",
  "increased iron ion transport",
  "increased lateral pseudopodium formation",
  "increased lateral pseudopodium retraction",
  "increased lipid droplet formation",
  "increased lower cup size",
  "increased lysosomal pH",
  "increased lysosomal protein degradation",
  "increased lysosome size",
  "increased macroautophagy",
  "increased macropinocytosis",
  "increased membrane ruffling",
  "increased microtubule nucleation",
  "increased migratory slug length",
  "increased migratory slug size",
  "increased mitochondrial fission",
  "increased mitochondrial fusion",
  "increased mound size",
  "increased myo-inositol level",
  "increased myosin II assembly",
  "increased negative chemotaxis",
  "increased number of autophagosomes",
  "increased number of centrosomes",
  "increased number of contractile vacuoles",
  "increased number of early culminant tips",
  "increased number of microtubule organizing centers",
  "increased number of mitochondria",
  "increased number of mounds",
  "increased number of mound tips",
  "increased number of pinosomes",
  "increased number of tip-organizers",
  "increased oscillatory cAMP signaling",
  "increased outer basal disc size",
  "increased peptidyl-proline 4-dioxygenase activity",
  "increased phagocytosis",
  "increased phagolysosome size",
  "increased phosphatase activity",
  "increased phosphatidylinositol 3-kinase/protein kinase B signal transduction",
  "increased phosphatidylinositol synthesis",
  "increased phototaxis",
  "increased pinocytosis",
  "increased post-lysosomal vacuole size",
  "increased pre-miRNA processing",
  "increased prespore cell differentiation",
  "increased prespore gene expression",
  "increased prestalk A cell differentiation",
  "increased prestalk B cell differentiation",
  "increased prestalk cell differentiation",
  "increased prestalk gene expression",
  "increased prestalk O cell differentiation",
  "increased prestalk U cell differentiation",
  "increased programmed cell death",
  "increased programmed necrotic cell death",
  "increased protein binding",
  "increased protein kinase activity",
  "increased protein kinase regulator activity",
  "increased protein level",
  "increased protein localization",
  "increased protein localization to actin wave",
  "increased protein localization to autophagosome",
  "increased protein localization to basolateral plasma membrane",
  "increased protein localization to cell-cell contact zone",
  "increased protein localization to cell cortex",
  "increased protein localization to cell surface",
  "increased protein localization to centrosome",
  "increased protein localization to clathrin-coated pit",
  "increased protein localization to cleavage furrow",
  "increased protein localization to contractile vacuole",
  "increased protein localization to contractile vacuole membrane",
  "increased protein localization to cytoplasm",
  "increased protein localization to cytoplasmic vesicle",
  "increased protein localization to endolysosome",
  "increased protein localization to filopodium",
  "increased protein localization to leading edge",
  "increased protein localization to lysosomal membrane",
  "increased protein localization to lysosome",
  "increased protein localization to macropinosome",
  "increased protein localization to microtubule organizing center",
  "increased protein localization to microtubules",
  "increased protein localization to mitotic spindle",
  "increased protein localization to mitotic spindle midzone",
  "increased protein localization to nuclear envelope",
  "increased protein localization to nucleolus",
  "increased protein localization to nucleus",
  "increased protein localization to phagocytic vesicle",
  "increased protein localization to plasma membrane",
  "increased protein localization to post-lysosomal vacuole",
  "increased protein localization to pseudopodium",
  "increased protein localization to trailing edge",
  "increased protein modification",
  "increased protein secretion",
  "increased protein stabilization",
  "increased protein tyrosine kinase activity",
  "increased protein tyrosine phosphatase activity",
  "increased pseudopodium formation",
  "increased pseudopodium size",
  "increased Rab protein signal transduction",
  "increased Rac protein signal transduction",
  "increased Rap protein signal transduction",
  "increased Ras protein signal transduction",
  "increased rate of endocytosis",
  "increased regulation of intracellular pH",
  "increased regulation of MAPK cascade",
  "increased resistance to 5-Fluoroorotic acid",
  "increased resistance to alendronic acid",
  "increased resistance to bleomycin",
  "increased resistance to carboplatin",
  "increased resistance to cheating during chimeric sorocarp development",
  "increased resistance to cisplatin",
  "increased resistance to hydroxyurea",
  "increased resistance to naringenin",
  "increased resistance to nocodazole",
  "increased resistance to N-Phenylthiourea",
  "increased resistance to phleomycin",
  "increased resistance to spectinomycin",
  "increased resistance to valproic acid",
  "increased response to cAMP",
  "increased response to DIF-1",
  "increased response to lithium",
  "increased secretion of lysosomal enzymes",
  "increased single-strand break repair",
  "increased slug migration",
  "increased small GTPase-mediated signal transduction",
  "increased sorus size",
  "increased spore size",
  "increased sporulation",
  "increased stalk cell differentiation",
  "increased stalk length",
  "increased stalk width",
  "increased standing slug length",
  "increased substrate adhesion-dependent cell spreading",
  "increased superoxide generation",
  "increased taxis",
  "increased thermotaxis",
  "increased TORC2 signaling",
  "increased translation",
  "increased upper cup size",
  "increased vegetative cell size",
  "mitotic G1 phase arrest",
  "mitotic M phase arrest",
  "precocious aggregation",
  "precocious cellular hyperosmotic response",
  "precocious cellular hypotonic response",
  "precocious contractile vacuole discharge",
  "precocious culmination",
  "precocious development",
  "precocious development of tipped mound",
  "precocious gene expression",
  "precocious mitotic spindle elongation",
  "precocious phagosome acidification",
  "precocious prespore gene expression",
  "precocious prestalk gene expression",
  "precocious response to DIF-1",
  "precocious spore germination",
  "precocious sporulation",
  "wild type",
]

export {
  INVALID_POSTAL_CODE_MESSAGE,
  INVALID_PHONE_MESSAGE,
  ENTITY_OPTIONS,
  PHENOTYPE_OPTIONS,
  QUALITY_OPTIONS,
}
