// flow-typed signature: 7cc7ec013a1d6f03ef7e31bfed44b66c
// flow-typed version: <<STUB>>/dicty-components-header-footer_v6.1.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dicty-components-header-footer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "dicty-components-header-footer" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "dicty-components-header-footer/es/components/Footer" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/es/components/Footer.test" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/es/components/Header" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/es/components/Header.test" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/es/data/footer" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/es/data/header" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/es/index" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/es/styles/FooterStyles" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/es/styles/headerStyles" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/es/styles/Link" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/lib/components/Footer" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/lib/components/Footer.test" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/lib/components/Header" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/lib/components/Header.test" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/lib/data/footer" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/lib/data/header" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/lib/index" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/lib/styles/FooterStyles" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/lib/styles/headerStyles" {
  declare module.exports: any
}

declare module "dicty-components-header-footer/lib/styles/Link" {
  declare module.exports: any
}

// Filename aliases
declare module "dicty-components-header-footer/es/components/Footer.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/es/components/Footer",
  >
}
declare module "dicty-components-header-footer/es/components/Footer.test.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/es/components/Footer.test",
  >
}
declare module "dicty-components-header-footer/es/components/Header.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/es/components/Header",
  >
}
declare module "dicty-components-header-footer/es/components/Header.test.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/es/components/Header.test",
  >
}
declare module "dicty-components-header-footer/es/data/footer.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/es/data/footer",
  >
}
declare module "dicty-components-header-footer/es/data/header.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/es/data/header",
  >
}
declare module "dicty-components-header-footer/es/index.js" {
  declare module.exports: $Exports<"dicty-components-header-footer/es/index">
}
declare module "dicty-components-header-footer/es/styles/FooterStyles.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/es/styles/FooterStyles",
  >
}
declare module "dicty-components-header-footer/es/styles/headerStyles.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/es/styles/headerStyles",
  >
}
declare module "dicty-components-header-footer/es/styles/Link.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/es/styles/Link",
  >
}
declare module "dicty-components-header-footer/lib/components/Footer.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/lib/components/Footer",
  >
}
declare module "dicty-components-header-footer/lib/components/Footer.test.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/lib/components/Footer.test",
  >
}
declare module "dicty-components-header-footer/lib/components/Header.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/lib/components/Header",
  >
}
declare module "dicty-components-header-footer/lib/components/Header.test.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/lib/components/Header.test",
  >
}
declare module "dicty-components-header-footer/lib/data/footer.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/lib/data/footer",
  >
}
declare module "dicty-components-header-footer/lib/data/header.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/lib/data/header",
  >
}
declare module "dicty-components-header-footer/lib/index.js" {
  declare module.exports: $Exports<"dicty-components-header-footer/lib/index">
}
declare module "dicty-components-header-footer/lib/styles/FooterStyles.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/lib/styles/FooterStyles",
  >
}
declare module "dicty-components-header-footer/lib/styles/headerStyles.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/lib/styles/headerStyles",
  >
}
declare module "dicty-components-header-footer/lib/styles/Link.js" {
  declare module.exports: $Exports<
    "dicty-components-header-footer/lib/styles/Link",
  >
}
