// flow-typed signature: c48261768570bf2b39c9ad130585b519
// flow-typed version: <<STUB>>/ProtVista_v2.x.x/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ProtVista'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "ProtVista" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "ProtVista/_site/javascripts/main" {
  declare module.exports: any
}

declare module "ProtVista/build/protvista" {
  declare module.exports: any
}

declare module "ProtVista/build/protvista.min.gz" {
  declare module.exports: any
}

declare module "ProtVista/build/protvista.min" {
  declare module.exports: any
}

declare module "ProtVista/coverage/lcov-report/prettify" {
  declare module.exports: any
}

declare module "ProtVista/coverage/lcov-report/sorter" {
  declare module.exports: any
}

declare module "ProtVista/gulpfile" {
  declare module.exports: any
}

declare module "ProtVista/snippets/simple_example" {
  declare module.exports: any
}

declare module "ProtVista/snippets/two_viewers_example" {
  declare module.exports: any
}

declare module "ProtVista/snippets/with_all_category_order" {
  declare module.exports: any
}

declare module "ProtVista/snippets/with_exclusions_external_data_and_config" {
  declare module.exports: any
}

declare module "ProtVista/snippets/with_exclusions" {
  declare module.exports: any
}

declare module "ProtVista/snippets/with_external_data_and_config" {
  declare module.exports: any
}

declare module "ProtVista/snippets/with_external_data" {
  declare module.exports: any
}

declare module "ProtVista/snippets/with_external_labeled_data" {
  declare module.exports: any
}

declare module "ProtVista/snippets/with_feature_selection" {
  declare module.exports: any
}

declare module "ProtVista/snippets/with_some_category_order" {
  declare module.exports: any
}

declare module "ProtVista/src/BasicViewer" {
  declare module.exports: any
}

declare module "ProtVista/src/CategoryFactory" {
  declare module.exports: any
}

declare module "ProtVista/src/CategoryFilterDialog" {
  declare module.exports: any
}

declare module "ProtVista/src/Constants" {
  declare module.exports: any
}

declare module "ProtVista/src/DataLoader" {
  declare module.exports: any
}

declare module "ProtVista/src/DownloadDataLoader" {
  declare module.exports: any
}

declare module "ProtVista/src/DownloadDialog" {
  declare module.exports: any
}

declare module "ProtVista/src/Evidence" {
  declare module.exports: any
}

declare module "ProtVista/src/FeatureFactory" {
  declare module.exports: any
}

declare module "ProtVista/src/FeaturesViewer" {
  declare module.exports: any
}

declare module "ProtVista/src/HighlightRegionDialog" {
  declare module.exports: any
}

declare module "ProtVista/src/NonOverlappingLayout" {
  declare module.exports: any
}

declare module "ProtVista/src/TooltipFactory" {
  declare module.exports: any
}

declare module "ProtVista/src/TrackFactory" {
  declare module.exports: any
}

declare module "ProtVista/src/VariantCategoryViewer" {
  declare module.exports: any
}

declare module "ProtVista/src/VariantFilterDialog" {
  declare module.exports: any
}

declare module "ProtVista/src/VariantLegendDialog" {
  declare module.exports: any
}

declare module "ProtVista/src/VariantViewer" {
  declare module.exports: any
}

declare module "ProtVista/src/ViewerHelper" {
  declare module.exports: any
}

declare module "ProtVista/test/dom/FeaturesData" {
  declare module.exports: any
}

declare module "ProtVista/test/dom/FeaturesViewerExclusionTest" {
  declare module.exports: any
}

declare module "ProtVista/test/dom/FeaturesViewerFlowTest" {
  declare module.exports: any
}

declare module "ProtVista/test/dom/index" {
  declare module.exports: any
}

declare module "ProtVista/test/unit/FeaturesViewerTest" {
  declare module.exports: any
}

// Filename aliases
declare module "ProtVista/_site/javascripts/main.js" {
  declare module.exports: $Exports<"ProtVista/_site/javascripts/main">
}
declare module "ProtVista/build/protvista.js" {
  declare module.exports: $Exports<"ProtVista/build/protvista">
}
declare module "ProtVista/build/protvista.min.gz.js" {
  declare module.exports: $Exports<"ProtVista/build/protvista.min.gz">
}
declare module "ProtVista/build/protvista.min.js" {
  declare module.exports: $Exports<"ProtVista/build/protvista.min">
}
declare module "ProtVista/coverage/lcov-report/prettify.js" {
  declare module.exports: $Exports<"ProtVista/coverage/lcov-report/prettify">
}
declare module "ProtVista/coverage/lcov-report/sorter.js" {
  declare module.exports: $Exports<"ProtVista/coverage/lcov-report/sorter">
}
declare module "ProtVista/gulpfile.js" {
  declare module.exports: $Exports<"ProtVista/gulpfile">
}
declare module "ProtVista/snippets/simple_example.js" {
  declare module.exports: $Exports<"ProtVista/snippets/simple_example">
}
declare module "ProtVista/snippets/two_viewers_example.js" {
  declare module.exports: $Exports<"ProtVista/snippets/two_viewers_example">
}
declare module "ProtVista/snippets/with_all_category_order.js" {
  declare module.exports: $Exports<"ProtVista/snippets/with_all_category_order">
}
declare module "ProtVista/snippets/with_exclusions_external_data_and_config.js" {
  declare module.exports: $Exports<
    "ProtVista/snippets/with_exclusions_external_data_and_config",
  >
}
declare module "ProtVista/snippets/with_exclusions.js" {
  declare module.exports: $Exports<"ProtVista/snippets/with_exclusions">
}
declare module "ProtVista/snippets/with_external_data_and_config.js" {
  declare module.exports: $Exports<
    "ProtVista/snippets/with_external_data_and_config",
  >
}
declare module "ProtVista/snippets/with_external_data.js" {
  declare module.exports: $Exports<"ProtVista/snippets/with_external_data">
}
declare module "ProtVista/snippets/with_external_labeled_data.js" {
  declare module.exports: $Exports<
    "ProtVista/snippets/with_external_labeled_data",
  >
}
declare module "ProtVista/snippets/with_feature_selection.js" {
  declare module.exports: $Exports<"ProtVista/snippets/with_feature_selection">
}
declare module "ProtVista/snippets/with_some_category_order.js" {
  declare module.exports: $Exports<
    "ProtVista/snippets/with_some_category_order",
  >
}
declare module "ProtVista/src/BasicViewer.js" {
  declare module.exports: $Exports<"ProtVista/src/BasicViewer">
}
declare module "ProtVista/src/CategoryFactory.js" {
  declare module.exports: $Exports<"ProtVista/src/CategoryFactory">
}
declare module "ProtVista/src/CategoryFilterDialog.js" {
  declare module.exports: $Exports<"ProtVista/src/CategoryFilterDialog">
}
declare module "ProtVista/src/Constants.js" {
  declare module.exports: $Exports<"ProtVista/src/Constants">
}
declare module "ProtVista/src/DataLoader.js" {
  declare module.exports: $Exports<"ProtVista/src/DataLoader">
}
declare module "ProtVista/src/DownloadDataLoader.js" {
  declare module.exports: $Exports<"ProtVista/src/DownloadDataLoader">
}
declare module "ProtVista/src/DownloadDialog.js" {
  declare module.exports: $Exports<"ProtVista/src/DownloadDialog">
}
declare module "ProtVista/src/Evidence.js" {
  declare module.exports: $Exports<"ProtVista/src/Evidence">
}
declare module "ProtVista/src/FeatureFactory.js" {
  declare module.exports: $Exports<"ProtVista/src/FeatureFactory">
}
declare module "ProtVista/src/FeaturesViewer.js" {
  declare module.exports: $Exports<"ProtVista/src/FeaturesViewer">
}
declare module "ProtVista/src/HighlightRegionDialog.js" {
  declare module.exports: $Exports<"ProtVista/src/HighlightRegionDialog">
}
declare module "ProtVista/src/NonOverlappingLayout.js" {
  declare module.exports: $Exports<"ProtVista/src/NonOverlappingLayout">
}
declare module "ProtVista/src/TooltipFactory.js" {
  declare module.exports: $Exports<"ProtVista/src/TooltipFactory">
}
declare module "ProtVista/src/TrackFactory.js" {
  declare module.exports: $Exports<"ProtVista/src/TrackFactory">
}
declare module "ProtVista/src/VariantCategoryViewer.js" {
  declare module.exports: $Exports<"ProtVista/src/VariantCategoryViewer">
}
declare module "ProtVista/src/VariantFilterDialog.js" {
  declare module.exports: $Exports<"ProtVista/src/VariantFilterDialog">
}
declare module "ProtVista/src/VariantLegendDialog.js" {
  declare module.exports: $Exports<"ProtVista/src/VariantLegendDialog">
}
declare module "ProtVista/src/VariantViewer.js" {
  declare module.exports: $Exports<"ProtVista/src/VariantViewer">
}
declare module "ProtVista/src/ViewerHelper.js" {
  declare module.exports: $Exports<"ProtVista/src/ViewerHelper">
}
declare module "ProtVista/test/dom/FeaturesData.js" {
  declare module.exports: $Exports<"ProtVista/test/dom/FeaturesData">
}
declare module "ProtVista/test/dom/FeaturesViewerExclusionTest.js" {
  declare module.exports: $Exports<
    "ProtVista/test/dom/FeaturesViewerExclusionTest",
  >
}
declare module "ProtVista/test/dom/FeaturesViewerFlowTest.js" {
  declare module.exports: $Exports<"ProtVista/test/dom/FeaturesViewerFlowTest">
}
declare module "ProtVista/test/dom/index.js" {
  declare module.exports: $Exports<"ProtVista/test/dom/index">
}
declare module "ProtVista/test/unit/FeaturesViewerTest.js" {
  declare module.exports: $Exports<"ProtVista/test/unit/FeaturesViewerTest">
}
