FROM node:22-alpine3.20 AS base

FROM base AS builder
ARG BUILD_STATE="development"
RUN apk update
RUN apk add --no-cache libc6-compat 
# Set working directory
WORKDIR /app
RUN yarn global add turbo@1.13.3
COPY . .
RUN mv /app/apps/dicty-frontpage-mui5/.env.${BUILD_STATE} /app/apps/dicty-frontpage/.env.production
RUN turbo prune --scope=dicty-frontpage-mui5 --docker

# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer
RUN apk update
RUN apk add --no-cache libc6-compat git
WORKDIR /app

# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/yarn.lock ./yarn.lock
RUN yarn install --ignore-engines --network-timeout 1000000 

# Build the project
COPY --from=builder /app/out/full/ .
RUN yarn turbo run build --filter=dicty-frontpage-mui5


FROM golang:1.22.6-alpine3.20

RUN apk update \
  && apk add git \
  && git clone https://github.com/dictyBase/static-server.git \
  && cd static-server \
  && go build -o /usr/local/bin/app 
WORKDIR /www
COPY --from=installer /app/apps/dicty-frontpage-mui5/dist ./
ENV PORT 3000
EXPOSE 3000
ENTRYPOINT ["/usr/local/bin/app", "run", "-f", "/www", "-p", "3000", "--sf", "/assets", "--sub-url", "mui5"]
