FROM node:22-alpine3.20 AS base

FROM base AS builder
ARG BUILD_STATE="development"
RUN apk update
RUN apk add --no-cache libc6-compat 
# Set working directory
WORKDIR /app
RUN yarn global add turbo@1.13.3
COPY . .
RUN mv /app/apps/publication/.env.${BUILD_STATE} /app/apps/publication/.env.production
RUN turbo prune --scope=publication --docker

# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer
RUN apk update
RUN apk add --no-cache libc6-compat git
WORKDIR /app

# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/yarn.lock ./yarn.lock
RUN yarn install --ignore-engines --network-timeout 1000000 

# Build the project
COPY --from=builder /app/out/full/ .
RUN yarn turbo run build --filter=publication


FROM golang:1.22.6-alpine3.20 AS go-builder

RUN apk update \
  && apk add git \
  && git clone https://github.com/dictyBase/static-server.git \
  && cd static-server \
  && go build -o /usr/local/bin/app 

FROM alpine:3.20

WORKDIR /www
COPY --from=installer /app/apps/publication/dist ./
COPY --from=go-builder /usr/local/bin/app /usr/local/bin/app
ENV PORT 3000
EXPOSE 3000
ENTRYPOINT ["/usr/local/bin/app", "run", "-f", "/www", "--sub-url", "/publication", "-p", "3000", "--sf", "/assets"]
