export { default as RecentNews } from "./frontpage/RecentNewsContainer"
export { default as BrowseNews } from "./BrowseNews"
export { default as NewsPage } from "./NewsPage"
export { default as CreateNews } from "./CreateNews"
export { default as UpdateNews } from "./UpdateNews"
