name: Node CI Staging
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: build staging docker image
        run: docker build -t dictybase/genomepage:staging-$(git rev-parse --short HEAD) -f docker/staging/Dockerfile .
      - name: push staging image to docker hub
        run: docker push dictybase/genomepage:staging-$(git rev-parse --short HEAD)
