name: Visual testing
on:
  pull_request:
    types: [edited, labeled, opened, synchronize, reopened]
    # only run when src files have changed
    paths:
      - "src/**"
  push:
    branches:
      - develop
jobs:
  percy:
    runs-on: ubuntu-20.04
    steps:
      - name: set up node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.16.1
      - name: check out code
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          mv src/common/utils/clientConfig.sample.ts src/common/utils/clientConfig.ts
          yarn install
      - name: run cypress and percy tests
        run: yarn cypress:ci
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
