name: Styleguide Build
on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy-styleguide:
    if: ${{ false }}
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install and build styleguide
        run: |
          mv common/utils/clientConfig.sample.ts common/utils/clientConfig.ts
          yarn install
          yarn styleguide:build
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./styleguide
