export * from "footer/src/components/Footer"
export * from "footer/src/components/FooterLink"
export * from "footer/src/types"
export * from "footer/src/data/footerData"
export * from "footer/src/styles/footerStyles"
