name: Node CI Develop
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dictybase/publication:ericdev-test-$(git rev-parse --short HEAD)
          file: docker/Dockerfile
          build-args: graphql_server=https://ericgraphql.dictybase.dev,func_server=https://ericfunc.dictybase.dev,client_keys=https://raw.githubusercontent.com/dictybase-playground/client-keys/2.0.0/clientConfig.eric.js,ga_tracking_id=-UA-146763741-1
