name: Audit live site
on:
  push:
    branches:
      - develop
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Audit live URL
        uses: docker://dictybase/lighthouse-audit:latest
        with:
          url: "https://eric.dictybase.dev/publication/26088819"
      - name: Upload results as an artifact
        uses: actions/upload-artifact@master
        with:
          name: report
          path: "./report"
