name: Node CI Develop
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      - name: check out code
        uses: actions/checkout@v2
      - name: rename config file
        run: mv common/utils/clientConfig.sample.ts common/utils/clientConfig.ts
      - name: install
        run: yarn install
      - name: rescript
        run: yarn re:build
      - name: run eslint
        run: yarn lint
      - name: run typescript build 
        run: yarn tsc
      - name: unit tests
        run: yarn test-coverage
        env:
          CI: true
      - name: upload test coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: run build
        run: yarn build
