name: Continuos integration
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts'
      - name: check out code
        uses: actions/checkout@v3
      - name: rename config file
        run: mv common/utils/clientConfig.sample.ts common/utils/clientConfig.ts
      - name: install
        run: yarn install
      - name: rescript
        run: yarn re:build
      - name: run eslint
        run: yarn lint
      - name: run typescript build 
        run: yarn tsc
      - name: unit tests
        run: yarn test-coverage
        env:
          CI: true
      - name: upload test coverage to codecov
        uses: codecov/codecov-action@v3
      - name: run build
        run: yarn build
  call-docker-build:
    needs: test
    uses: dictyBase/workflows/.github/workflows/docker-build-push-custom.yaml@develop
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      dockerfile: "docker/Dockerfile.dev"
