// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@material-ui/core";

function PublicationHeader(Props) {
  return React.createElement(Core.Box, {
              children: React.createElement(Core.Typography, {
                    align: "center",
                    children: "dictyBase Literature",
                    variant: "h2"
                  }),
              mb: 2,
              mt: 2
            });
}

var make = PublicationHeader;

export {
  make ,
  
}
/* react Not a pure module */
