export const data = [
  {
    type: "biological_process",
    id: "GO:0000281",
    attributes: {
      date: "20120522",
      evidence_code: "IMP",
      goterm: "mitotic cytokinesis",
      qualifier: "acts_upstream_of_or_within",
      publication: "PMID:12499361",
      with: null,
      extensions: null,
      assigned_by: "dictyBase",
    },
  },
  {
    type: "biological_process",
    id: "GO:0000902",
    attributes: {
      date: "20051219",
      evidence_code: "IMP",
      goterm: "cell morphogenesis",
      qualifier: "acts_upstream_of_or_within",
      publication: "PMID:12499361",
      with: null,
      extensions: null,
      assigned_by: "dictyBase",
    },
  },
  {
    type: "biological_process",
    id: "GO:0006909",
    attributes: {
      date: "20030723",
      evidence_code: "IMP",
      goterm: "phagocytosis",
      qualifier: "acts_upstream_of_or_within",
      publication: "PMID:12499361",
      with: null,
      extensions: null,
      assigned_by: "dictyBase",
    },
  },
  {
    type: "biological_process",
    id: "GO:0006909",
    attributes: {
      date: "20120926",
      evidence_code: "IMP",
      goterm: "phagocytosis",
      qualifier: "acts_upstream_of_or_within",
      publication: "PMID:22219373",
      with: null,
      extensions: null,
      assigned_by: "dictyBase",
    },
  },
  {
    type: "biological_process",
    id: "GO:0007015",
    attributes: {
      date: "20030723",
      evidence_code: "IMP",
      goterm: "actin filament organization",
      qualifier: "acts_upstream_of_or_within",
      publication: "PMID:12499361",
      with: null,
      extensions: null,
      assigned_by: "dictyBase",
    },
  },
  {
    type: "biological_process",
    id: "GO:0031589",
    attributes: {
      date: "20050922",
      evidence_code: "IMP",
      goterm: "cell-substrate adhesion",
      qualifier: "acts_upstream_of_or_within",
      publication: "PMID:12499361",
      with: null,
      extensions: null,
      assigned_by: "dictyBase",
    },
  },
  {
    type: "biological_process",
    id: "GO:0031589",
    attributes: {
      date: "20110914",
      evidence_code: "IMP",
      goterm: "cell-substrate adhesion",
      qualifier: "acts_upstream_of_or_within",
      publication: "PMID:21441344",
      with: null,
      extensions: null,
      assigned_by: "dictyBase",
    },
  },
  {
    type: "biological_process",
    id: "GO:0034394",
    attributes: {
      date: "20120926",
      evidence_code: "IMP",
      goterm: "protein localization to cell surface",
      qualifier: "acts_upstream_of_or_within",
      publication: "PMID:22219373",
      with: null,
      extensions: [
        {
          connectedXrefs: [
            { db: "UniProtKB", id: "Q54KF7", relation: "has_direct_input" },
          ],
        },
      ],
      assigned_by: "dictyBase",
    },
  },
  {
    type: "biological_process",
    id: "GO:0050821",
    attributes: {
      date: "20120926",
      evidence_code: "IMP",
      goterm: "protein stabilization",
      qualifier: "acts_upstream_of_or_within",
      publication: "PMID:22219373",
      with: null,
      extensions: [
        {
          connectedXrefs: [
            { db: "UniProtKB", id: "Q54KF7", relation: "has_direct_input" },
          ],
        },
      ],
      assigned_by: "dictyBase",
    },
  },
  {
    type: "cellular_component",
    id: "GO:0005886",
    attributes: {
      date: "20120522",
      evidence_code: "IDA",
      goterm: "plasma membrane",
      qualifier: "colocalizes_with",
      publication: "PMID:21441344",
      with: null,
      extensions: null,
      assigned_by: "dictyBase",
    },
  },
  {
    type: "molecular_function",
    id: "GO:0005515",
    attributes: {
      date: "20110913",
      evidence_code: "IPI",
      goterm: "protein binding",
      qualifier: "enables",
      publication: "PMID:21441344",
      with: [{ connectedXrefs: [{ db: "UniProtKB", id: "Q54HG2" }] }],
      extensions: null,
      assigned_by: "dictyBase",
    },
  },
  {
    type: "biological_process",
    id: "GO:0006909",
    attributes: {
      date: "20180721",
      evidence_code: "IEA",
      goterm: "phagocytosis",
      qualifier: "involved_in",
      publication: "GO_REF:0000037",
      with: [{ connectedXrefs: [{ db: "UniProtKB-KW", id: "KW-0581" }] }],
      extensions: null,
      assigned_by: "UniProt",
    },
  },
  {
    type: "biological_process",
    id: "GO:0007155",
    attributes: {
      date: "20180721",
      evidence_code: "IEA",
      goterm: "cell adhesion",
      qualifier: "involved_in",
      publication: "GO_REF:0000037",
      with: [{ connectedXrefs: [{ db: "UniProtKB-KW", id: "KW-0130" }] }],
      extensions: null,
      assigned_by: "UniProt",
    },
  },
  {
    type: "cellular_component",
    id: "GO:0005886",
    attributes: {
      date: "20180721",
      evidence_code: "IEA",
      goterm: "plasma membrane",
      qualifier: "part_of",
      publication: "GO_REF:0000037",
      with: [{ connectedXrefs: [{ db: "UniProtKB-KW", id: "KW-1003" }] }],
      extensions: null,
      assigned_by: "UniProt",
    },
  },
  {
    type: "cellular_component",
    id: "GO:0005886",
    attributes: {
      date: "20180721",
      evidence_code: "IEA",
      goterm: "plasma membrane",
      qualifier: "part_of",
      publication: "GO_REF:0000039",
      with: [{ connectedXrefs: [{ db: "UniProtKB-SubCell", id: "SL-0039" }] }],
      extensions: null,
      assigned_by: "UniProt",
    },
  },
  {
    type: "cellular_component",
    id: "GO:0005887",
    attributes: {
      date: "20160811",
      evidence_code: "IBA",
      goterm: "integral component of plasma membrane",
      qualifier: "part_of",
      publication: "PAINT_REF:11219",
      with: [{ connectedXrefs: [{ db: "PANTHER", id: "PTN001677757" }] }],
      extensions: null,
      assigned_by: "GO_Central",
    },
  },
  {
    type: "cellular_component",
    id: "GO:0005938",
    attributes: {
      date: "20120522",
      evidence_code: "IDA",
      goterm: "cell cortex",
      qualifier: "part_of",
      publication: "PMID:12499361",
      with: null,
      extensions: null,
      assigned_by: "dictyBase",
    },
  },
  {
    type: "cellular_component",
    id: "GO:0015629",
    attributes: {
      date: "20120522",
      evidence_code: "IDA",
      goterm: "actin cytoskeleton",
      qualifier: "part_of",
      publication: "PMID:21441344",
      with: null,
      extensions: null,
      assigned_by: "dictyBase",
    },
  },
  {
    type: "cellular_component",
    id: "GO:0016020",
    attributes: {
      date: "20180721",
      evidence_code: "IEA",
      goterm: "membrane",
      qualifier: "part_of",
      publication: "GO_REF:0000037",
      with: [{ connectedXrefs: [{ db: "UniProtKB-KW", id: "KW-0472" }] }],
      extensions: null,
      assigned_by: "UniProt",
    },
  },
  {
    type: "cellular_component",
    id: "GO:0016021",
    attributes: {
      date: "20180721",
      evidence_code: "IEA",
      goterm: "integral component of membrane",
      qualifier: "part_of",
      publication: "GO_REF:0000037",
      with: [{ connectedXrefs: [{ db: "UniProtKB-KW", id: "KW-0812" }] }],
      extensions: null,
      assigned_by: "UniProt",
    },
  },
]
