FROM node:lts-bullseye-slim as builder

ENV CLIENT_KEYS='https://raw.githubusercontent.com/dictybase-playground/client-keys/2.0.1/clientConfig.sidd.js'

RUN apt-get -qq update 

WORKDIR /app

COPY package.json ./
COPY tsconfig.json ./
COPY yarn.lock ./
COPY .merlin ./
COPY bsconfig.json ./
COPY next-env.d.ts ./
COPY next.config.js ./
COPY .env.development ./.env.production
RUN yarn

ADD common common
ADD components components
ADD pages pages
ADD public public
ADD styles styles
ADD docker docker
ADD $CLIENT_KEYS /usr/src/app/common/utils/clientConfig.js
RUN yarn build

FROM node:lts-bullseye-slim as runner
WORKDIR /app
COPY --from=builder /app/package.json ./
COPY --from=builder /app/yarn.lock ./
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder  /app/.next/standalone ./
COPY --from=builder  /app/.next/static ./.next/static
EXPOSE 3000
CMD ["yarn","start"]
