FROM node:lts-alpine3.17

ENV NEXT_PUBLIC_BASENAME="/publication"
ENV NEXT_PUBLIC_GA_TRACKING_ID=""
ENV NEXT_PUBLIC_GRAPHQL_SERVER=https://graphql.dictybase.dev
ENV NEXT_PUBLIC_FOOTER_JSON='https://raw.githubusercontent.com/dictyBase/migration-data/master/footer/footer-condensed.json'
ENV NEXT_PUBLIC_NAVBAR_JSON='https://raw.githubusercontent.com/dictyBase/migration-data/master/navbar/navbar.json'
ENV NEXT_PUBLIC_DEPLOY_ENV="development"
ENV CLIENT_KEYS='https://raw.githubusercontent.com/dictybase-playground/client-keys/2.0.1/clientConfig.sidd.js'

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json ./
COPY tsconfig.json ./
COPY yarn.lock ./
COPY .merlin ./
COPY bsconfig.json ./
COPY next-env.d.ts ./
COPY next.config.js ./
RUN yarn

ADD common common
ADD components components
ADD pages pages
ADD public public
ADD styles styles
ADD docker docker
ADD $CLIENT_KEYS /usr/src/app/common/utils/clientConfig.js
RUN yarn build

FROM dictybase/static-server:2.2.1
RUN mkdir /www
WORKDIR /www
COPY --from=0 /usr/src/app/build ./
ENTRYPOINT ["/usr/local/bin/app", "run", "-f", "/www", "--sub-url", "/publication"]
