// navbar types
export const FETCH_NAVBAR_REQUEST = "FETCH_NAVBAR_REQUEST"
export const FETCH_NAVBAR_SUCCESS = "FETCH_NAVBAR_SUCCESS"
export const FETCH_NAVBAR_FAILURE = "FETCH_NAVBAR_FAILURE"
// footer types
export const FETCH_FOOTER_REQUEST = "FETCH_FOOTER_REQUEST"
export const FETCH_FOOTER_SUCCESS = "FETCH_FOOTER_SUCCESS"
export const FETCH_FOOTER_FAILURE = "FETCH_FOOTER_FAILURE"
