apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:-{{.IMAGE_TAG}}"
  artifacts:
    - image: dictybase/publication
      docker:
        dockerfile: docker/staging/Dockerfile
  local: {}
profiles:
  - name: ericdev
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:ericdev-{{.IMAGE_TAG}}"
      artifacts:
        - image: dictybase/publication
          docker:
            dockerfile: docker/eric-dev/Dockerfile
  - name: devsidd
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:devsidd-{{.IMAGE_TAG}}"
      artifacts:
        - image: dictybase/publication
          docker:
            dockerfile: docker/sidd-dev/Dockerfile
