name: Building (Pull Request)
on: [pull_request, workflow_dispatch]
jobs:
  build-frontpage:
    name: Build Frontpage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Check out Code
        uses: actions/checkout@v6
      - name: Install Turbo
        run: yarn global add turbo@1.13.3
      - name: Set Up Environment
        run: mv apps/dicty-frontpage/.env.development apps/dicty-frontpage/.env.production
      - name: Prune Application
        run: turbo prune --scope=dicty-frontpage --out-dir=./dfp
      - name: Install Dependencies
        working-directory: dfp
        run: yarn install --ignore-engines
      - name: Build Application
        working-directory: dfp
        run: yarn turbo run build --filter=dicty-frontpage
      - name: run Lighthouse CI
        env: 
          LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: dfp
        run: |
          npm install -g @lhci/cli@0.15.x
          lhci autorun --config="../.lighthouserc.json"
  build-stock-center:
    name: Build Stock Center
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Check out Code
        uses: actions/checkout@v6
      - name: Install Turbo
        run: yarn global add turbo@1.13.3
      - name: Set Up Environment
        run: mv apps/stock-center/.env.development apps/stock-center/.env.production
      - name: Prune Application
        run: turbo prune --scope=stock-center --out-dir=./dsc
      - name: Install Dependencies
        working-directory: dsc
        run: yarn install --ignore-engines
      - name: Build Application
        working-directory: dsc
        run: yarn turbo run build --filter=stock-center
  build-genomepage:
    name: Build Genome Page
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Check out Code
        uses: actions/checkout@v6
      - name: Install Turbo
        run: yarn global add turbo@1.13.3
      - name: Set Up Environment
        run: mv apps/genome-page/.env.development apps/genome-page/.env.production
      - name: Prune Application
        run: turbo prune --scope=genomepage --out-dir=./gp
      - name: Install Dependencies
        working-directory: gp
        run: yarn install --ignore-engines
      - name: Build Application
        working-directory: gp
        run: yarn turbo run build --filter=genomepage
  build-publication:
    name: Build Publication
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Check out Code
        uses: actions/checkout@v6
      - name: Install Turbo
        run: yarn global add turbo@1.13.3
      - name: Set Up Environment
        run: mv apps/publication/.env.development apps/publication/.env.production
      - name: Prune Application
        run: turbo prune --scope=publication --out-dir=pub
      - name: Install Dependencies
        working-directory: pub
        run: yarn install --ignore-engines
      - name: Build Application
        working-directory: pub
        run: yarn turbo run build --filter=publication
