name: continuous integration
on:
  push:
    branches:
      - develop
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: check out code
        uses: actions/checkout@v4
      - name: install
        run: yarn --ignore-engines
      - name: unit tests
        run: yarn coverage
      - name: upload test coverage to codecov
        uses: codecov/codecov-action@v5
        with: 
          token: ${{ secrets.CODECOV }}
  call-deploy:
    needs: test
    strategy:
      matrix:
        include:
          - app: frontpage
            docker_image: dicty-frontpage
            dockerfile: docker/Dockerfile.frontpage
          - app: stockcenter
            docker_image: stock-center
            dockerfile: docker/Dockerfile.stock-center
          - app: publication
            docker_image: publication
            dockerfile: docker/Dockerfile.publication
          - app: genomepage
            docker_image: genomepage
            dockerfile: docker/Dockerfile.genomepage
    uses: dictyBase/workflows/.github/workflows/composite-deploy.yaml@develop
    secrets: inherit
    with:
       project: frontend_application
       stack: experiments
       application_type: frontend
       app: ${{ matrix.app }}
       repository: ${{ github.repository }}
       ref: ${{ github.ref_name }}
       docker_image: ${{ matrix.docker_image }}
       dockerfile: ${{ matrix.dockerfile }}
       cluster: ${{ vars.DEV_STAGING_CLUSTER }}
       cluster_state_storage: ${{ vars.DEV_STAGING_KOPS_STATE_STORAGE }}
