name: continuous integration
on:
  push:
    branches:
      - develop
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: check out code
        uses: actions/checkout@v6
      - name: install
        run: yarn --ignore-engines
      - name: unit tests
        run: yarn coverage
      - name: upload test coverage to codecov
        uses: codecov/codecov-action@v5
        with: 
          token: ${{ secrets.CODECOV }}
  call-deploy:
    needs: test
    uses: dictyBase/workflows/.github/workflows/composite-deploy.yaml@develop
    secrets: inherit
    with:
       project: frontend_application
       stack: experiments
       application_type: frontend
       app: frontpage:stockcenter:publication:genomepage
       repository: ${{ github.repository }}
       ref: ${{ github.ref_name }}
       docker_image: dicty-frontpage:stock-center:publication:genomepage
       dockerfile: docker/Dockerfile.frontpage:docker/Dockerfile.stock-center:docker/Dockerfile.publication:docker/Dockerfile.genomepage
       cluster: ${{ vars.DEV_STAGING_CLUSTER }}
       cluster_state_storage: ${{ vars.DEV_STAGING_KOPS_STATE_STORAGE }}
