name: Integration Tests (Pull Request)
on: [pull_request, workflow_dispatch]
jobs:
  dicty-frontpage-e2e:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Check out Code
        uses: actions/checkout@v4
      - name: install
        run: yarn install --ignore-engines
      - name: install playwright
        run: yarn playwright install --with-deps
      - name: integration tests
        run: yarn e2e --filter=dicty-frontpage
  stock-center-e2e:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Check out Code
        uses: actions/checkout@v4
      - name: install
        run: yarn install --ignore-engines
      - name: install playwright
        run: yarn playwright install --with-deps
      - name: integration tests
        run: yarn e2e --filter=stock-center
  genomepage-e2e:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Check out Code
        uses: actions/checkout@v4
      - name: install
        run: yarn install --ignore-engines
      - name: install playwright
        run: yarn playwright install --with-deps
      - name: integration tests
        run: yarn e2e --filter=genomepage
  publication-e2e:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Check out Code
        uses: actions/checkout@v4
      - name: install
        run: yarn install --ignore-engines
      - name: install playwright
        run: yarn playwright install --with-deps
      - name: integration tests
        run: yarn e2e --filter=publication
