name: Oxlint
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run Oxlint
        run: npx --yes -f=github --config=apps/dicty-frontpage/.oxlintrc.json oxlint@1.6.0 
