name: staging integration
on:
  push:
    branches:
      - staging
jobs:
  call-frontpage-docker-build:
    uses: dictyBase/workflows/.github/workflows/docker-build-push-mode.yaml@develop
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      dockerfile: "docker/Dockerfile.frontpage"
      dockerrepo: "dictybase/dicty-frontpage"
      build_state: staging
  call-dsc-docker-build:
    uses: dictyBase/workflows/.github/workflows/docker-build-push-mode.yaml@develop
    secrets: inherit
    with:
      build_state: staging
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      dockerfile: "docker/Dockerfile.stock-center"
      dockerrepo: "dictybase/stock-center"
  call-publication-docker-build:
    uses: dictyBase/workflows/.github/workflows/docker-build-push-mode.yaml@develop
    secrets: inherit
    with:
      build_state: staging
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      dockerfile: "docker/Dockerfile.publication"
      dockerrepo: "dictybase/publication"
