name: staging integration
on:
  push:
    branches:
      - staging
jobs:
  call-frontpage-deploy:
    uses: dictyBase/workflows/.github/workflows/composite-deploy.yaml@develop
    secrets: inherit
    with:
      app: frontpage
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      docker_image: dicty-frontpage
      dockerfile: "docker/Dockerfile.frontpage"
      cluster: ${{ vars.DEV_STAGING_CLUSTER }}
      cluster_state_storage: ${{ vars.DEV_STAGING_KOPS_STATE_STORAGE }}
      project: frontend_application
      application_type: frontend
      environment: staging
  call-stockcenter-deploy:
    needs: call-frontpage-deploy
    uses: dictyBase/workflows/.github/workflows/composite-deploy.yaml@develop
    secrets: inherit
    with:
      app: stockcenter
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      docker_image: stock-center
      dockerfile: docker/Dockerfile.stock-center
      cluster: ${{ vars.DEV_STAGING_CLUSTER }}
      cluster_state_storage: ${{ vars.DEV_STAGING_KOPS_STATE_STORAGE }}
      project: frontend_application
      application_type: frontend
      environment: staging
  call-publication-deploy:
    needs: call-stockcenter-deploy
    uses: dictyBase/workflows/.github/workflows/composite-deploy.yaml@develop
    secrets: inherit
    with:
      app: publication
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      dockerfile: docker/Dockerfile.publication
      docker_image: publication
      cluster: ${{ vars.DEV_STAGING_CLUSTER }}
      cluster_state_storage: ${{ vars.DEV_STAGING_KOPS_STATE_STORAGE }}
      project: frontend_application
      application_type: frontend
      environment: staging
